$ErrorActionPreference="Stop"
# Use deterministic .NET SHA-256 in this fixture; CI must not depend on
# PowerShell module/cmdlet discovery while exercising sandboxed recovery seams.
function Get-FixtureHash {
  param([Parameter(Position=0)][string]$Path,[string]$LiteralPath,[string]$Algorithm="SHA256")
  if($Algorithm -ne "SHA256"){throw "fixture hash algorithm must be SHA256"}
  $file=if($PSBoundParameters.ContainsKey("LiteralPath")){$LiteralPath}else{$Path}
  $stream=[IO.File]::OpenRead($file);$sha=[Security.Cryptography.SHA256]::Create()
  try { [pscustomobject]@{Hash=([BitConverter]::ToString($sha.ComputeHash($stream)).Replace("-",""))} }
  finally { $sha.Dispose();$stream.Dispose() }
}
# Extracted bootstrap functions run in this isolated fixture scope. Preserve
# their Get-FileHash contract without relying on PowerShell module autoloading.
Set-Alias -Name Get-FileHash -Value Get-FixtureHash -Scope Script
$scriptPath=Join-Path $PSScriptRoot "start-catdesk-stack.ps1";$source=Get-Content -LiteralPath $scriptPath -Raw;$tokens=$null;$errors=$null
$ast=[System.Management.Automation.Language.Parser]::ParseInput($source,[ref]$tokens,[ref]$errors);if($errors.Count){throw "bootstrap script did not parse"}
# Reboot regression: Windows PowerShell can evaluate parameter-default
# expressions before $PSScriptRoot is populated. Workspace-relative defaults
# must therefore be inert in param(...) and resolved only after binding.
$parameterPrefix=$source.Substring(0,$source.IndexOf('$ErrorActionPreference',[StringComparison]::Ordinal));if($parameterPrefix -match '\$PSScriptRoot'){throw "bootstrap parameter defaults still depend on PSScriptRoot"};if($parameterPrefix -notmatch '\[string\]\$Workspace\s*=\s*""'){throw "Workspace default is not late-bound"};if($parameterPrefix -notmatch '\[string\]\$BuildFingerprintPath\s*=\s*""'){throw "build fingerprint default is not late-bound"};if($source -notmatch '\$Workspace\s*=\s*Join-Path\s+\$PSScriptRoot\s+"\.\."'){throw "Workspace late binding is missing"};if($source -notmatch '\$BuildFingerprintPath\s*=\s*Join-Path\s+\$Workspace\s+"target\\release\\catdesk\.exe\.sha256"'){throw "build fingerprint late binding is missing"}
# T-0340: wake-runtime repair participates in one-command recovery, so Python
# launcher discovery must not bypass the repair script's bounded native child
# primitive. Keep this source-level guard next to the approved recovery harness
# so a future direct `& py.exe ...` regression fails repository acceptance.
$wakeRepairPath=Join-Path $PSScriptRoot "repair_wake_bridge_environment.ps1";$wakeRepairSource=Get-Content -LiteralPath $wakeRepairPath -Raw;$wrTokens=$null;$wrErrors=$null;$wakeRepairAst=[System.Management.Automation.Language.Parser]::ParseInput($wakeRepairSource,[ref]$wrTokens,[ref]$wrErrors);if($wrErrors.Count){throw "wake repair script did not parse"};$resolvePythonNode=$wakeRepairAst.Find({param($n)$n -is [System.Management.Automation.Language.FunctionDefinitionAst] -and $n.Name -eq 'Resolve-Python3'},$true);if($null -eq $resolvePythonNode){throw "missing Resolve-Python3"};$resolvePythonSource=$resolvePythonNode.Extent.Text;if($resolvePythonSource -match '&\s*\$py(?:\.Source)?'){throw "wake Python launcher discovery bypassed bounded native execution"};if($resolvePythonSource -notmatch 'Invoke-NativeQuiet\s+-Executable\s+\$py'){throw "wake Python launcher discovery did not use bounded native execution"};if($resolvePythonSource -notmatch '-TimeoutMilliseconds\s+5000'){throw "wake Python launcher discovery lost its explicit bounded timeout"};if($resolvePythonSource -match 'Get-Command\s+(?:py|python)\.exe'){throw "wake Python discovery regained caller command-resolution authority"};if($resolvePythonSource -match '\$env:(?:PATH|LOCALAPPDATA|USERPROFILE)'){throw "wake Python discovery regained caller environment path authority"};if($resolvePythonSource -notmatch '\[System\.Environment\]::GetFolderPath'){throw "wake Python discovery lost trusted special-folder derivation"};$trustedPythonNode=$wakeRepairAst.Find({param($n)$n -is [System.Management.Automation.Language.FunctionDefinitionAst] -and $n.Name -eq 'Get-TrustedPythonExecutableCandidate'},$true);if($null -eq $trustedPythonNode){throw "missing trusted Python executable candidate validator"};$trustedPythonSource=$trustedPythonNode.Extent.Text;if($trustedPythonSource -notmatch 'ReparsePoint'){throw "trusted Python candidate validation lost reparse-point rejection"};if($trustedPythonSource -notmatch 'OrdinalIgnoreCase'){throw "trusted Python candidate validation lost exact resolved-path comparison"};$fakePythonPath=Join-Path ([IO.Path]::GetTempPath()) ("catdesk-t0344-path-hijack-"+[Guid]::NewGuid().ToString("N"));New-Item -ItemType Directory -Path $fakePythonPath|Out-Null;Set-Content -LiteralPath (Join-Path $fakePythonPath 'py.exe') -Value 'fake';Set-Content -LiteralPath (Join-Path $fakePythonPath 'python.exe') -Value 'fake';$priorPath=$env:PATH;try{$env:PATH=$fakePythonPath+';'+$priorPath;if($resolvePythonSource -match [regex]::Escape($fakePythonPath)){throw "wake Python resolver captured caller PATH shadow"};if($resolvePythonSource -match 'Get-Command'){throw "wake Python resolver can still consult caller PATH"}}finally{$env:PATH=$priorPath;Remove-Item -LiteralPath $fakePythonPath -Recurse -Force -ErrorAction SilentlyContinue}
# T-0354: wake-repair Python/venv/pip children may themselves spawn descendants. Recovery must never return from a timed-out repair while descendant mutation continues.
$containedTypeNode=$wakeRepairAst.Find({param($n)$n -is [System.Management.Automation.Language.FunctionDefinitionAst] -and $n.Name -eq 'Initialize-WakeRepairContainedProcessType'},$true);if($null -eq $containedTypeNode){throw "missing wake-repair descendant containment type"};$containedTypeSource=$containedTypeNode.Extent.Text;if($containedTypeSource -notmatch 'JOB_OBJECT_LIMIT_KILL_ON_JOB_CLOSE'){throw "wake-repair containment lost kill-on-job-close policy"};if($containedTypeSource -notmatch 'AssignProcessToJobObject'){throw "wake-repair containment lost process-tree assignment"};if($containedTypeSource -notmatch 'CloseHandle\(job\)'){throw "wake-repair containment lost job-close termination boundary"};$invokeNativeNode=$wakeRepairAst.Find({param($n)$n -is [System.Management.Automation.Language.FunctionDefinitionAst] -and $n.Name -eq 'Invoke-NativeQuiet'},$true);if($null -eq $invokeNativeNode){throw "missing bounded wake native invocation"};$invokeNativeSource=$invokeNativeNode.Extent.Text;if($invokeNativeSource -notmatch 'WakeRepairContainedProcess'){throw "wake native invocation bypassed descendant containment"};$convertNativeNode=$wakeRepairAst.Find({param($n)$n -is [System.Management.Automation.Language.FunctionDefinitionAst] -and $n.Name -eq 'ConvertTo-NativeArgument'},$true);if($null -eq $convertNativeNode){throw "missing wake native argument encoder"};.([scriptblock]::Create($convertNativeNode.Extent.Text));.([scriptblock]::Create($containedTypeNode.Extent.Text));.([scriptblock]::Create($invokeNativeNode.Extent.Text));$marker=Join-Path ([IO.Path]::GetTempPath()) ("catdesk-t0354-descendant-"+[Guid]::NewGuid().ToString("N")+'.txt');$currentPowerShell=(Get-Process -Id $PID).Path;$childScript="Start-Sleep -Milliseconds 900; [IO.File]::WriteAllText('"+$marker.Replace("'","''")+"','escaped')";$childEncoded=[Convert]::ToBase64String([Text.Encoding]::Unicode.GetBytes($childScript));$parentScript="Start-Process -FilePath '"+$currentPowerShell.Replace("'","''")+"' -ArgumentList '-NoProfile','-NonInteractive','-EncodedCommand','"+$childEncoded+"' -WindowStyle Hidden; Start-Sleep -Seconds 30";$parentEncoded=[Convert]::ToBase64String([Text.Encoding]::Unicode.GetBytes($parentScript));$timedOut=$false;try{$null=Invoke-NativeQuiet -Executable $currentPowerShell -Arguments @('-NoProfile','-NonInteractive','-EncodedCommand',$parentEncoded) -TimeoutMilliseconds 250}catch{if($_.Exception.Message -notmatch 'contained process tree was killed'){throw};$timedOut=$true};if(-not $timedOut){throw "wake-repair descendant containment fixture did not hit timeout"};Start-Sleep -Milliseconds 1200;if(Test-Path -LiteralPath $marker){Remove-Item -LiteralPath $marker -Force -ErrorAction SilentlyContinue;throw "wake-repair descendant escaped timeout containment"}
$releaseRecoveryPath=Join-Path $PSScriptRoot "catdesk-release-recovery.ps1";$releaseRecoverySource=Get-Content -LiteralPath $releaseRecoveryPath -Raw;$rrTokens=$null;$rrErrors=$null;$null=[System.Management.Automation.Language.Parser]::ParseInput($releaseRecoverySource,[ref]$rrTokens,[ref]$rrErrors);if($rrErrors.Count){throw "release recovery helper did not parse"};. $releaseRecoveryPath
foreach($name in @("Resolve-TrustedBootstrapHelperPath","Get-RemainingReadinessMilliseconds","ConvertTo-NativeCommandLineArgument","Initialize-BoundedNativeProcessType","Invoke-BoundedTunnelClient","Invoke-BoundedCodexProbe","Resolve-TrustedCurrentUserCodexCommand","Resolve-TrustedWindowsCommandPromptPath","Resolve-TrustedWindowsPowerShellPath","Invoke-BoundedRecoveryHelper","Invoke-BoundedWindowsInventoryProbe","Invoke-SilentLoopbackHttp","Get-VerifiedBuildFingerprint","Get-CanonicalCatDeskIdentity","Read-OfficialRuntimeProcessMode","Get-ConfiguredRuntimeAlias","Find-TunnelClient","Get-ConfiguredLocalMcp","Get-LoopbackCatDeskListener","Test-CatDeskPinnedProcessMatchesRecoveryIdentity","Get-CatDeskListenerProcessInstanceForRecovery","Test-CatDeskListenerStillMatchesRecoveryCandidate","Stop-CatDeskListenerProcessForRecovery","Get-CatDeskDaemonProcessCandidates","Get-CatDeskDaemonProcessInstanceForRecovery","Stop-StaleCanonicalCatDeskDaemonForRecovery","Test-CodexOnDemandPrerequisites","Test-WakeBridgeRuntime","Invoke-WakeBridgeRuntimeRepair","Invoke-OrderedOfficialRuntimeMigration","New-LocalMcpReadinessResult","Get-LocalMcpReadiness","Test-LocalMcpReadiness","Get-AuthoritativeRuntimeBase","New-OfficialRuntimeVerificationResult","Get-OfficialRuntimeVerification","Test-OfficialRuntimeVerified","Wait-FullStackReadiness","Get-RedactedReadinessFailureGate","Save-RedactedRecoveryEvidence","Invoke-InterruptedPromotionPairRecovery","Get-CanonicalReleaseRecoveryAssessment","Stop-CanonicalPathCatDeskForReleaseRepair","Repair-CanonicalReleaseForRecovery","Test-CatDeskInteractiveDesktop","Resolve-VerifiedInstalledWakeHost","Start-CatDeskWakeHost","Start-CatDeskBinagotchyGui","Invoke-CanonicalStackBootstrap")){$node=$ast.Find({param($n)$n -is [System.Management.Automation.Language.FunctionDefinitionAst] -and $n.Name -eq $name},$true);if($null -eq $node){throw "missing $name"};.([scriptblock]::Create($node.Extent.Text))}
$dispatch=$ast.Find({param($n)$n -is [System.Management.Automation.Language.FunctionDefinitionAst] -and $n.Name -eq "Invoke-BootstrapSeam"},$true);.([scriptblock]::Create($dispatch.Extent.Text));$script:BootstrapSeams=@{};$script:MaxMcpReplyBytes=1048576;$script:MaxTunnelClientOutputBytes=1048576;$script:MaxTunnelClientCommandMilliseconds=30000;$script:MaxCodexProbeOutputBytes=65536;$script:MaxCodexProbeMilliseconds=5000;$script:MaxRecoveryHelperOutputBytes=65536;$script:MaxWakeRuntimeProbeMilliseconds=5000;$script:MaxWakeRepairMilliseconds=1500000;$script:MaxOfficialMigrationMilliseconds=30000;$script:MaxInterruptedPromotionRecoveryMilliseconds=30000;$script:MaxWindowsInventoryProbeMilliseconds=5000;$script:MaxWindowsInventoryProbeOutputBytes=65536;$script:WindowsInventoryProbeHelperPath=Join-Path $PSScriptRoot 'query-catdesk-windows-inventory.ps1'
$root=Join-Path ([IO.Path]::GetTempPath()) ("catdesk-t0052-r2-"+[Guid]::NewGuid().ToString("N"));New-Item -ItemType Directory -Path $root|Out-Null
$hadTunnelRef=Test-Path Env:CATDESK_OPENAI_TUNNEL_ID;$priorTunnelRef=$env:CATDESK_OPENAI_TUNNEL_ID;$hadControlRef=Test-Path Env:CONTROL_PLANE_API_KEY;$priorControlRef=$env:CONTROL_PLANE_API_KEY;$hadCodexExecutable=Test-Path Env:CATDESK_CODEX_CLI_EXECUTABLE;$priorCodexExecutable=$env:CATDESK_CODEX_CLI_EXECUTABLE
try {
  $codexShim=Join-Path $root "codex-test.cmd";[IO.File]::WriteAllText($codexShim,"@echo off`r`necho Logged in using ChatGPT 1>&2`r`nexit /b 0`r`n")
  $env:CATDESK_CODEX_CLI_EXECUTABLE=$codexShim
  Test-CodexOnDemandPrerequisites
  # T-0343: caller PATH is not Codex executable-selection authority. With the
  # explicit recovery override absent, only the deterministic current-user npm
  # command directory may satisfy discovery.
  $trustedCodexRoot=Join-Path $root 'trusted-codex';$fakeCodexRoot=Join-Path $root 'fake-codex-path';New-Item -ItemType Directory -Path $trustedCodexRoot,$fakeCodexRoot -Force|Out-Null;$trustedCodex=Join-Path $trustedCodexRoot 'codex.cmd';$fakeCodex=Join-Path $fakeCodexRoot 'codex.cmd';[IO.File]::WriteAllText($trustedCodex,"@echo off`r`nexit /b 0`r`n");[IO.File]::WriteAllText($fakeCodex,"@echo off`r`nexit /b 0`r`n")
  $priorPathCodexDiscovery=$env:PATH;Remove-Item Env:CATDESK_CODEX_CLI_EXECUTABLE -ErrorAction SilentlyContinue;try{$env:PATH=$fakeCodexRoot+';'+$priorPathCodexDiscovery;$resolvedCodex=Resolve-TrustedCurrentUserCodexCommand -CurrentUserNpmRoot $trustedCodexRoot;if(-not ([string]$resolvedCodex.Source).Equals([IO.Path]::GetFullPath($trustedCodex),[StringComparison]::OrdinalIgnoreCase)){throw "trusted current-user Codex command was not selected"};if(([string]$resolvedCodex.Source).Equals([IO.Path]::GetFullPath($fakeCodex),[StringComparison]::OrdinalIgnoreCase)){throw "PATH Codex hijack was accepted"}}finally{$env:PATH=$priorPathCodexDiscovery;$env:CATDESK_CODEX_CLI_EXECUTABLE=$codexShim}
  $codexResolverNode=$ast.Find({param($n)$n -is [System.Management.Automation.Language.FunctionDefinitionAst] -and $n.Name -eq 'Resolve-TrustedCurrentUserCodexCommand'},$true);if($null -eq $codexResolverNode){throw "missing Resolve-TrustedCurrentUserCodexCommand"};$codexResolverSource=$codexResolverNode.Extent.Text;if($codexResolverSource -match 'Get-Command\s+["'']?codex|\$env:PATH|\bnpm\s+(root|prefix|config)'){throw "Codex prerequisite discovery retained caller PATH/npm authority"}
  # T-0338: Codex wrappers are discovery results, not authority to choose the
  # interpreter that executes them. A caller-controlled ComSpec/PATH must not
  # capture .cmd/.bat execution, and the Codex probe must not retain PSHOME.
  $fakeComSpec=Join-Path $root "fake-comspec.exe";[IO.File]::WriteAllText($fakeComSpec,"not a command processor image")
  $priorComSpec=$env:ComSpec;$priorPathForCodex=$env:PATH;try{$env:ComSpec=$fakeComSpec;$env:PATH=(Split-Path -Parent $fakeComSpec)+";"+$priorPathForCodex;Test-CodexOnDemandPrerequisites;$trustedCmd=Resolve-TrustedWindowsCommandPromptPath;$expectedCmd=[IO.Path]::GetFullPath((Join-Path ([Environment]::SystemDirectory) "cmd.exe"));if(-not $trustedCmd.Equals($expectedCmd,[StringComparison]::OrdinalIgnoreCase)){throw "Codex wrapper did not resolve fixed OS command processor"};if($trustedCmd.Equals([IO.Path]::GetFullPath($fakeComSpec),[StringComparison]::OrdinalIgnoreCase)){throw "Codex wrapper accepted ComSpec hijack"}}finally{$env:ComSpec=$priorComSpec;$env:PATH=$priorPathForCodex}
  $codexProbeNode=$ast.Find({param($n)$n -is [System.Management.Automation.Language.FunctionDefinitionAst] -and $n.Name -eq 'Invoke-BoundedCodexProbe'},$true);if($null -eq $codexProbeNode){throw "missing Invoke-BoundedCodexProbe"};$codexProbeSource=$codexProbeNode.Extent.Text;if($codexProbeSource -match '\$env:ComSpec|\$PSHOME|Get-Command\s+(cmd|powershell)'){throw "Codex wrapper retained caller-selected interpreter authority"};foreach($requiredResolver in @('Resolve-TrustedWindowsCommandPromptPath','Resolve-TrustedWindowsPowerShellPath')){if($codexProbeSource -notmatch [regex]::Escape($requiredResolver)){throw "Codex wrapper did not use $requiredResolver"}}
  [IO.File]::WriteAllText($codexShim,"@echo off`r`necho failed 1>&2`r`nexit /b 7`r`n")
  try{Test-CodexOnDemandPrerequisites;throw "nonzero Codex probe accepted"}catch{if($_.Exception.Message -match "nonzero Codex probe accepted"){throw}}
  # T-0332: Codex is an on-demand prerequisite, not recovery authority. A
  # wedged CLI wrapper must fail within its own bounded probe rather than hang
  # plan/recover before daemon/runtime convergence can even begin.
  [IO.File]::WriteAllText($codexShim,"@echo off`r`n:loop`r`ngoto loop`r`n")
  $script:MaxCodexProbeMilliseconds=250;$timer=[Diagnostics.Stopwatch]::StartNew();try{Test-CodexOnDemandPrerequisites;throw "hanging Codex probe accepted"}catch{if($_.Exception.Message -match "hanging Codex probe accepted"){throw};if($_.Exception.Message -notmatch "bounded timeout"){throw}};$timer.Stop();$script:MaxCodexProbeMilliseconds=5000;if($timer.ElapsedMilliseconds -gt 3000){throw "hanging Codex probe exceeded hard timeout"}
  # A hanging fake native client must be killed by the bounded process helper.
  $nativePowerShell=Join-Path $PSHOME "powershell.exe";if(-not(Test-Path -LiteralPath $nativePowerShell -PathType Leaf)){$nativePowerShell=(Get-Command powershell -ErrorAction Stop).Source}
  $timer=[Diagnostics.Stopwatch]::StartNew();try{Invoke-BoundedTunnelClient -ClientPath $nativePowerShell -Arguments @("-NoProfile","-Command","Start-Sleep -Seconds 10") -TimeoutMilliseconds 250|Out-Null;throw "hanging tunnel client was accepted"}catch{if($_.Exception.Message -match "hanging tunnel client was accepted"){throw};if($_.Exception.Message -notmatch "bounded timeout"){throw}};$timer.Stop();if($timer.ElapsedMilliseconds -gt 3000){throw "hanging tunnel client exceeded hard timeout"}
  # Recovery mutations that invoke project-owned PowerShell helpers must resolve
  # Windows PowerShell from the fixed OS system directory, never caller PATH.
  $fakePowerShellRoot=Join-Path $root "fake-powershell";New-Item -ItemType Directory -Path $fakePowerShellRoot|Out-Null;$fakePowerShell=Join-Path $fakePowerShellRoot "powershell.exe";[IO.File]::WriteAllText($fakePowerShell,"not a powershell image")
  $priorPath=$env:PATH;try{$env:PATH=$fakePowerShellRoot+";"+$priorPath;$trustedPowerShell=Resolve-TrustedWindowsPowerShellPath;$expectedTrusted=[IO.Path]::GetFullPath((Join-Path ([Environment]::SystemDirectory) "WindowsPowerShell\v1.0\powershell.exe"));if(-not $trustedPowerShell.Equals($expectedTrusted,[StringComparison]::OrdinalIgnoreCase)){throw "recovery helper did not resolve fixed OS PowerShell"};if($trustedPowerShell.Equals([IO.Path]::GetFullPath($fakePowerShell),[StringComparison]::OrdinalIgnoreCase)){throw "recovery helper accepted PATH PowerShell hijack"}}finally{$env:PATH=$priorPath}
  foreach($functionName in @('Invoke-WakeBridgeRuntimeRepair','Invoke-OrderedOfficialRuntimeMigration')){$functionNode=$ast.Find({param($n)$n -is [System.Management.Automation.Language.FunctionDefinitionAst] -and $n.Name -eq $functionName},$true);if($null -eq $functionNode){throw "missing $functionName"};if($functionNode.Extent.Text -match '\$PSHOME|Get-Command\s+power(shell)?'){throw "$functionName retained caller-selected PowerShell authority"};if($functionNode.Extent.Text -notmatch 'Resolve-TrustedWindowsPowerShellPath'){throw "$functionName did not use trusted PowerShell resolver"};if($functionNode.Extent.Text -notmatch 'Resolve-TrustedBootstrapHelperPath'){throw "$functionName lost exact project-helper identity validation"}}
  # T-0350: project-owned scripts that participate in public one-command recovery
  # are execution authority. Their leaf identity must not be redirectable through
  # a reparse point even though their containing workspace is intentionally dirty.
  $helperResolverNode=$ast.Find({param($n)$n -is [System.Management.Automation.Language.FunctionDefinitionAst] -and $n.Name -eq 'Resolve-TrustedBootstrapHelperPath'},$true);if($null -eq $helperResolverNode){throw "missing Resolve-TrustedBootstrapHelperPath"};$helperResolverSource=$helperResolverNode.Extent.Text;foreach($requiredHelperGuard in @('Get-Item','ReparsePoint','GetFullPath','OrdinalIgnoreCase')){if($helperResolverSource -notmatch [regex]::Escape($requiredHelperGuard)){throw "trusted project-helper identity validation lost $requiredHelperGuard"}}
  $trustedSyntheticHelper=Join-Path $root 'trusted-helper.ps1';[IO.File]::WriteAllText($trustedSyntheticHelper,'# fixture');$resolvedSyntheticHelper=Resolve-TrustedBootstrapHelperPath -Path $trustedSyntheticHelper -FailureMessage 'synthetic helper identity invalid';if(-not $resolvedSyntheticHelper.Equals([IO.Path]::GetFullPath($trustedSyntheticHelper),[StringComparison]::OrdinalIgnoreCase)){throw "trusted project helper exact path was rejected"}
  # Independent wake ownership is inert while the selector is absent/legacy,
  # but once selected public recovery must heal only the immutable installed
  # WakeHost named by the per-user pointer and exact SHA-256.
  $wakeLifecycleRoot=Join-Path $root 'wake-lifecycle';$wakeSelectorDir=Join-Path $wakeLifecycleRoot '.catdesk\wake-bridge';$wakeInstallRoot=Join-Path $root 'wake-install';New-Item -ItemType Directory -Path $wakeSelectorDir,$wakeInstallRoot -Force|Out-Null;$wakeHostActions=[Collections.Generic.List[string]]::new();$script:BootstrapSeams['WakeHostStart']={param($wakeHostPath)[void]$wakeHostActions.Add([string]$wakeHostPath)};if(Start-CatDeskWakeHost -Root $wakeLifecycleRoot -WakeRoot $wakeInstallRoot){throw 'missing wake-owner selector started WakeHost'};[IO.File]::WriteAllText((Join-Path $wakeSelectorDir 'owner.json'),'{"schemaVersion":1,"owner":"legacy_python"}');if(Start-CatDeskWakeHost -Root $wakeLifecycleRoot -WakeRoot $wakeInstallRoot){throw 'legacy wake owner started independent WakeHost'};$wakeVersion='1.0.0-test';$wakeVersionDir=Join-Path $wakeInstallRoot ('versions\'+$wakeVersion);New-Item -ItemType Directory -Path $wakeVersionDir -Force|Out-Null;$wakeHostBinary=Join-Path $wakeVersionDir 'CatDeskWakeHost.exe';[IO.File]::WriteAllText($wakeHostBinary,'wake-host-fixture');$wakeHostHash=(Get-FixtureHash -LiteralPath $wakeHostBinary -Algorithm SHA256).Hash.ToLowerInvariant();@{schemaVersion=1;directory=$wakeVersion;hostSha256=$wakeHostHash;binagotchySha256=('b'*64)}|ConvertTo-Json -Compress|Set-Content -LiteralPath (Join-Path $wakeInstallRoot 'current.json') -Encoding utf8;[IO.File]::WriteAllText((Join-Path $wakeSelectorDir 'owner.json'),'{"schemaVersion":1,"owner":"independent_v1"}');if(-not(Start-CatDeskWakeHost -Root $wakeLifecycleRoot -WakeRoot $wakeInstallRoot)){throw 'independent wake owner did not heal installed WakeHost'};if($wakeHostActions.Count -ne 1 -or -not $wakeHostActions[0].Equals([IO.Path]::GetFullPath($wakeHostBinary),[StringComparison]::OrdinalIgnoreCase)){throw 'WakeHost recovery did not use exact installed executable'};[IO.File]::WriteAllText($wakeHostBinary,'tampered');try{$null=Start-CatDeskWakeHost -Root $wakeLifecycleRoot -WakeRoot $wakeInstallRoot;throw 'tampered WakeHost was started'}catch{if($_.Exception.Message -match 'tampered WakeHost was started'){throw};if($_.Exception.Message -ne 'WakeHost installation hash mismatch'){throw}};if($wakeHostActions.Count -ne 1){throw 'tampered WakeHost crossed start boundary'};$script:BootstrapSeams.Remove('WakeHostStart')
  $releaseHelperBootstrapPrefix=$source.Substring(0,[Math]::Min($source.Length,4000));if($releaseHelperBootstrapPrefix -notmatch 'Resolve-TrustedBootstrapHelperPath\s+-Path\s+\(Join-Path\s+\$PSScriptRoot\s+''catdesk-release-recovery\.ps1''\)'){throw "release recovery helper can execute before exact identity validation"}
  $promotionIdentityNode=$ast.Find({param($n)$n -is [System.Management.Automation.Language.FunctionDefinitionAst] -and $n.Name -eq 'Invoke-InterruptedPromotionPairRecovery'},$true);if($promotionIdentityNode.Extent.Text -notmatch 'Resolve-TrustedBootstrapHelperPath'){throw "promotion rollback helper lost exact project-helper identity validation"}
  $inventoryIdentityNode=$ast.Find({param($n)$n -is [System.Management.Automation.Language.FunctionDefinitionAst] -and $n.Name -eq 'Invoke-BoundedWindowsInventoryProbe'},$true);if($null -eq $inventoryIdentityNode -or $inventoryIdentityNode.Extent.Text -notmatch 'Resolve-TrustedBootstrapHelperPath'){throw "Windows inventory helper lost shared exact project-helper identity validation"}
  # T-0355: the provisioned wake venv interpreter is itself executable recovery
  # authority. It must cross the same exact non-reparse leaf boundary before the
  # bounded health probe can execute it; leaf existence alone is insufficient.
  $wakeRuntimeIdentityNode=$ast.Find({param($n)$n -is [System.Management.Automation.Language.FunctionDefinitionAst] -and $n.Name -eq 'Test-WakeBridgeRuntime'},$true);if($null -eq $wakeRuntimeIdentityNode){throw "missing Test-WakeBridgeRuntime"};$wakeRuntimeIdentitySource=$wakeRuntimeIdentityNode.Extent.Text;if($wakeRuntimeIdentitySource -notmatch 'Resolve-TrustedBootstrapHelperPath'){throw "wake runtime interpreter lost exact executable identity validation"};if($wakeRuntimeIdentitySource -match 'Test-Path\s+-LiteralPath\s+\$python\s+-PathType\s+Leaf'){throw "wake runtime interpreter regressed to leaf-existence-only validation"};if($wakeRuntimeIdentitySource -notmatch 'Invoke-BoundedRecoveryHelper\s+-FileName\s+\$python'){throw "wake runtime interpreter bypassed bounded execution after identity validation"}
  # Independent Wake selected: read only installed/hash-pinned WakeHost status,
  # never treat retired Python availability as independent host readiness or
  # repair it as a fallback. Keep this source guard close to the old runtime probe.
  if($wakeRuntimeIdentitySource -notmatch 'Resolve-VerifiedInstalledWakeHost' -or -not $wakeRuntimeIdentitySource.Contains("-Arguments @('status')")) { throw 'independent wake status probe lost exact installed host boundary' }
  $wakeRepairAstNode=$ast.Find({param($n)$n -is [System.Management.Automation.Language.FunctionDefinitionAst] -and $n.Name -eq 'Invoke-WakeBridgeRuntimeRepair'},$true)
  if($null -eq $wakeRepairAstNode -or $wakeRepairAstNode.Extent.Text -notmatch 'Resolve-VerifiedInstalledWakeHost' -or -not $wakeRepairAstNode.Extent.Text.Contains('if ($independentHost)')) { throw 'independent wake can fall through to retired Python repair' }
  # T-0333: recovery helper subprocesses inherit the same hard bounded-process
  # semantics. A wedged child PowerShell must return control to recover.
  $timer=[Diagnostics.Stopwatch]::StartNew();try{Invoke-BoundedRecoveryHelper -FileName $nativePowerShell -Arguments @("-NoProfile","-Command","Start-Sleep -Seconds 10") -TimeoutMilliseconds 250 -FailureMessage "synthetic recovery helper failed"|Out-Null;throw "hanging recovery helper was accepted"}catch{if($_.Exception.Message -match "hanging recovery helper was accepted"){throw};if($_.Exception.Message -notmatch "bounded helper timed out"){throw}};$timer.Stop();if($timer.ElapsedMilliseconds -gt 3000){throw "hanging recovery helper exceeded hard timeout"}
  # T-0347: Windows networking/CIM providers are observations, not authority to
  # hold one-command recovery indefinitely. They must execute only in the fixed
  # trusted PowerShell child and return through a finite parent deadline.
  $inventoryNode=$ast.Find({param($n)$n -is [System.Management.Automation.Language.FunctionDefinitionAst] -and $n.Name -eq 'Invoke-BoundedWindowsInventoryProbe'},$true);if($null -eq $inventoryNode){throw "missing Invoke-BoundedWindowsInventoryProbe"};$inventorySource=$inventoryNode.Extent.Text;if($inventorySource -notmatch 'Resolve-TrustedWindowsPowerShellPath'){throw "Windows inventory probe lost trusted PowerShell authority"};if($inventorySource -notmatch 'BoundedNativeProcess'){throw "Windows inventory probe lost bounded native execution"};if($inventorySource -notmatch 'MaxWindowsInventoryProbeMilliseconds'){throw "Windows inventory probe lost explicit parent deadline"};if($source -match '(?m)^\s*\$[^\r\n]*Get-NetTCPConnection|(?m)^\s*\$[^\r\n]*Get-CimInstance'){throw "recovery parent retained direct Windows provider inventory query"}
  $inventoryHelperSource=Get-Content -LiteralPath (Join-Path $PSScriptRoot 'query-catdesk-windows-inventory.ps1') -Raw;if($inventoryHelperSource -notmatch 'ReadLoopbackListeners' -or $inventoryHelperSource -notmatch 'Get-LocalProcessInventoryRow'){throw "Windows inventory helper lost fixed read-only provider coverage"};$daemonReaderIndex=$inventoryHelperSource.IndexOf('LocalProcessCommandLineReader',[StringComparison]::Ordinal);$daemonTokenIndex=$inventoryHelperSource.IndexOf("--catdesk-daemon",[StringComparison]::Ordinal);$daemonCapIndex=$inventoryHelperSource.IndexOf('if ($relevant.Count -gt 64)',[StringComparison]::Ordinal);if($daemonReaderIndex -lt 0 -or $daemonTokenIndex -lt 0 -or $daemonCapIndex -lt 0 -or $daemonReaderIndex -gt $daemonTokenIndex -or $daemonTokenIndex -gt $daemonCapIndex){throw "Windows daemon inventory does not narrow command-line candidates before the relevant-row cap"};if($inventoryHelperSource -notmatch "Select-Object -First 257" -or $inventoryHelperSource -notmatch "too many CatDesk process rows are ambiguous"){throw "Windows daemon inventory lost its bounded raw snapshot refusal"};$inventoryHang=Join-Path $root 'hanging-inventory.ps1';[IO.File]::WriteAllText($inventoryHang,"param([string]`$Mode,[int]`$Port,[int]`$ProcessId) while(`$true){ Start-Sleep -Seconds 1 }");$script:MaxWindowsInventoryProbeMilliseconds=250;$timer=[Diagnostics.Stopwatch]::StartNew();try{$null=Invoke-BoundedWindowsInventoryProbe -Mode Daemons -HelperPath $inventoryHang;throw "hanging Windows inventory provider was accepted"}catch{if($_.Exception.Message -match "was accepted"){throw};if($_.Exception.Message -notmatch "bounded timeout"){throw}};$timer.Stop();$script:MaxWindowsInventoryProbeMilliseconds=5000;if($timer.ElapsedMilliseconds -gt 3000){throw "Windows inventory provider exceeded hard timeout"}
  # T-0336: an on-time wrapper can still leave a descendant holding inherited
  # stdout/stderr handles. The successful-parent capture drain must therefore be
  # bounded and fail closed instead of hanging recover after WaitForExit succeeds.
   $leakyChild='$p=New-Object Diagnostics.Process;$p.StartInfo.FileName=(Join-Path $PSHOME "powershell.exe");$p.StartInfo.Arguments="-NoProfile -NonInteractive -Command Start-Sleep -Seconds 5";$p.StartInfo.UseShellExecute=$false;[void]$p.Start();exit 0';$timer=[Diagnostics.Stopwatch]::StartNew();try{Invoke-BoundedRecoveryHelper -FileName $nativePowerShell -Arguments @("-NoProfile","-NonInteractive","-Command",$leakyChild) -TimeoutMilliseconds 5000 -FailureMessage "synthetic inherited-pipe helper failed"|Out-Null;throw "inherited-pipe helper was accepted"}catch{if($_.Exception.Message -match "inherited-pipe helper was accepted"){throw};if($_.Exception.Message -notmatch "output drain timed out"){throw}};$timer.Stop();if($timer.ElapsedMilliseconds -gt 3500){throw "inherited-pipe helper exceeded bounded output drain"}
  # T-0342: interrupted reviewed-promotion pair recovery participates directly in
  # one-command recover. Its project-owned PowerShell helper must therefore be a
  # bounded trusted-child boundary, not an in-process invocation that can wedge
  # the recovery command indefinitely.
  $promotionRecoveryNode=$ast.Find({param($n)$n -is [System.Management.Automation.Language.FunctionDefinitionAst] -and $n.Name -eq 'Invoke-InterruptedPromotionPairRecovery'},$true);if($null -eq $promotionRecoveryNode){throw "missing Invoke-InterruptedPromotionPairRecovery"};$promotionRecoverySource=$promotionRecoveryNode.Extent.Text;if($promotionRecoverySource -match '&\s*\$promotion'){throw "interrupted promotion recovery retained direct in-process execution"};if($promotionRecoverySource -notmatch 'Resolve-TrustedWindowsPowerShellPath'){throw "interrupted promotion recovery lost trusted PowerShell authority"};if($promotionRecoverySource -notmatch 'Invoke-BoundedRecoveryHelper'){throw "interrupted promotion recovery lost bounded helper execution"};if($promotionRecoverySource -notmatch 'MaxInterruptedPromotionRecoveryMilliseconds'){throw "interrupted promotion recovery lost its explicit parent deadline"};if($promotionRecoverySource -notmatch "'-RecoveryRollbackOnly'"){throw "interrupted promotion recovery can still launch a detached promotion handoff descendant"}
  $promotionHangRoot=Join-Path $root 'promotion-hang';$promotionHangState=Join-Path $promotionHangRoot '.catdesk\promotion-recovery';$promotionHangScripts=Join-Path $promotionHangRoot 'scripts';New-Item -ItemType Directory -Path $promotionHangState,$promotionHangScripts -Force|Out-Null;[IO.File]::WriteAllText((Join-Path $promotionHangState 'promotion-transaction.json'),'{}');$promotionHangHelper=Join-Path $promotionHangScripts 'promote-reviewed-catdesk-build.ps1';[IO.File]::WriteAllText($promotionHangHelper,'param($BuildPath,$Workspace,[switch]$Execute,[switch]$RecoveryRollbackOnly) while($true){ Start-Sleep -Seconds 1 }');$script:MaxInterruptedPromotionRecoveryMilliseconds=250;$timer=[Diagnostics.Stopwatch]::StartNew();try{$null=Invoke-InterruptedPromotionPairRecovery -Root $promotionHangRoot;throw "hanging interrupted promotion recovery was accepted"}catch{if($_.Exception.Message -match "hanging interrupted promotion recovery was accepted"){throw};if($_.Exception.Message -notmatch "bounded helper timed out"){throw}};$timer.Stop();$script:MaxInterruptedPromotionRecoveryMilliseconds=30000;if($timer.ElapsedMilliseconds -gt 3000){throw "interrupted promotion recovery exceeded hard timeout"}
  $deadline=[DateTime]::UtcNow.AddMilliseconds(250);$remaining=Get-RemainingReadinessMilliseconds -Deadline $deadline -RequestedMilliseconds 5000;if($remaining -lt 1 -or $remaining -gt 250){throw "runtime command was not capped by readiness deadline"}
  $priorProgressPreference=$ProgressPreference;function Invoke-WebRequest { param($Uri,$Method,$ContentType,$Body,[switch]$UseBasicParsing,$MaximumRedirection,$TimeoutSec)if($ProgressPreference -ne "SilentlyContinue"){throw "loopback HTTP progress was not silent"};[pscustomobject]@{StatusCode=200;Content="{}"} };$ProgressPreference="Continue";Invoke-SilentLoopbackHttp -Uri "http://127.0.0.1:1/healthz"|Out-Null;if($ProgressPreference -ne "Continue"){throw "loopback HTTP progress preference was not restored"};$ProgressPreference=$priorProgressPreference
  # T-0341/T-0345: recovery tunnel-client discovery must not grant executable-selection
  # authority to caller PATH. Only an explicit operator path or CatDesk's durable
  # user-local installation identities may satisfy plan/recover discovery, and the
  # default durable candidates must retain exact non-reparse executable identity.
  $clientRoot=Join-Path $root "client-profile";$explicit=Join-Path $root "explicit.exe";$pathRoot=Join-Path $root "path-client";$pathClient=Join-Path $pathRoot "tunnel-client.exe";New-Item -ItemType Directory -Path $pathRoot -Force|Out-Null;[IO.File]::WriteAllText($explicit,"x");[IO.File]::WriteAllText($pathClient,"x")
  $priorTunnelDiscoveryPath=$env:PATH;try{$env:PATH=$pathRoot+";"+$priorTunnelDiscoveryPath;if((Find-TunnelClient -ExplicitPath $explicit -UserProfilePath $clientRoot) -ne (Resolve-Path $explicit).Path){throw "explicit client did not win"};if($null -ne (Find-TunnelClient -ExplicitPath (Join-Path $root "missing.exe") -UserProfilePath $clientRoot)){throw "PATH tunnel-client hijack was accepted"}}finally{$env:PATH=$priorTunnelDiscoveryPath}
  $findTunnelNode=$ast.Find({param($n)$n -is [System.Management.Automation.Language.FunctionDefinitionAst] -and $n.Name -eq 'Find-TunnelClient'},$true);if($null -eq $findTunnelNode){throw "missing Find-TunnelClient"};$findTunnelSource=$findTunnelNode.Extent.Text;if($findTunnelSource -match 'Get-Command'){throw "recovery tunnel-client discovery retained PATH authority"};if($findTunnelSource -notmatch 'ReparsePoint'){throw "default recovery tunnel-client discovery lost reparse-point rejection"};if($findTunnelSource -notmatch 'GetFullPath'){throw "default recovery tunnel-client discovery lost canonical full-path validation"};if($findTunnelSource -notmatch 'OrdinalIgnoreCase'){throw "default recovery tunnel-client discovery lost exact resolved-path identity comparison"};if($findTunnelSource -notmatch 'Get-Item\s+-LiteralPath\s+\$candidate\s+-Force'){throw "default recovery tunnel-client discovery lost file identity inspection"}
  $current=Join-Path $clientRoot ".catdesk\tools\tunnel-client\current";New-Item -ItemType Directory -Path $current -Force|Out-Null;$currentClient=Join-Path $current "tunnel-client.exe";[IO.File]::WriteAllText($currentClient,"x")
  if((Find-TunnelClient -ExplicitPath "" -UserProfilePath $clientRoot) -ne [IO.Path]::GetFullPath($currentClient)){throw "current user-local client was not selected"}
  Remove-Item -LiteralPath $currentClient -Force;$legacy=Join-Path $clientRoot ".catdesk\tools\tunnel-client";New-Item -ItemType Directory -Path $legacy -Force|Out-Null;$legacyClient=Join-Path $legacy "tunnel-client.exe";[IO.File]::WriteAllText($legacyClient,"x")
  if((Find-TunnelClient -ExplicitPath "" -UserProfilePath $clientRoot) -ne [IO.Path]::GetFullPath($legacyClient)){throw "legacy user-local client was not selected"};Remove-Item -LiteralPath $legacyClient -Force
  if($null -ne (Find-TunnelClient -ExplicitPath "" -UserProfilePath $clientRoot)){throw "missing client did not fail closed"}
  $route="route_abcdefghijklmnopqrstuv";$config=Join-Path $root "config.toml";$body="[mcp]`nbind_host = `"127.0.0.1`"`nport = 43123`nroute_id = `"$route`"`n[tunnel]`nmode = `"openai_secure_tunnel`"`n[openai_tunnel]`nprocess_mode = `"official_runtime`""
  [IO.File]::WriteAllText($config,$body,[Text.UTF8Encoding]::new($false));$local=Get-ConfiguredLocalMcp $config;if($local.Uri -notmatch "/mcp$"){throw "route-scoped endpoint missing"};if((Read-OfficialRuntimeProcessMode $config) -ne "official_runtime"){throw "official config rejected"}
  # Characterize raw loopback listener ownership without touching real machine sockets.
  $listenerBinary=Join-Path $root "listener-catdesk.exe";[IO.File]::WriteAllText($listenerBinary,"synthetic-listener");$listenerHash=(Get-FixtureHash $listenerBinary -Algorithm SHA256).Hash.ToLowerInvariant();$listenerCanonical=[pscustomobject]@{Path=(Resolve-Path $listenerBinary).Path;Sha256=$listenerHash}
  $script:listenerRows=@();$script:listenerCimRows=@();$script:daemonRows=@()
  # Production provider calls are now isolated in a bounded child. Characterize
  # the parent attribution logic with deterministic inventory rows through this
  # function replacement rather than consulting live host providers.
  function Invoke-BoundedWindowsInventoryProbe { param($Mode,$Port,$ProcessId,$HelperPath) if($Mode -eq 'Listener'){return @($script:listenerRows)};if($Mode -eq 'Process'){return @($script:listenerCimRows)};if($Mode -eq 'Daemons'){return @($script:daemonRows)};throw 'unexpected inventory mode' }
  $listenerCreated=[DateTime]::Parse('2026-09-07T00:00:00Z').ToUniversalTime();$selectedCreated=$listenerCreated.ToString('o');$pinnedSame=[pscustomobject]@{Handle=[IntPtr]1;StartTime=$listenerCreated;Path=$listenerBinary};if(-not(Test-CatDeskPinnedProcessMatchesRecoveryIdentity -Process $pinnedSame -SelectedCreation $selectedCreated -SelectedPath (Resolve-Path $listenerBinary).Path)){throw 'exact pinned process identity was rejected'};$pinnedReplacement=[pscustomobject]@{Handle=[IntPtr]2;StartTime=$listenerCreated.AddTicks(10);Path=$listenerBinary};if(Test-CatDeskPinnedProcessMatchesRecoveryIdentity -Process $pinnedReplacement -SelectedCreation $selectedCreated -SelectedPath (Resolve-Path $listenerBinary).Path){throw 'same-path replacement process instance at a distinct CIM creation time was accepted'};$script:listenerCimRows=@([pscustomobject]@{Name='catdesk.exe';ProcessId=7001;ExecutablePath=$listenerBinary;CommandLine="`"$listenerBinary`" --catdesk-daemon";CreationDate=$listenerCreated})
  $script:listenerRows=@([pscustomobject]@{LocalAddress="127.0.0.1";OwningProcess=7001});$singleListener=Get-LoopbackCatDeskListener -Port 43123 -Canonical $listenerCanonical;if($singleListener.Pid -ne 7001 -or -not $singleListener.MatchesCanonical -or [string]::IsNullOrWhiteSpace([string]$singleListener.CreationTimeUtc) -or $singleListener.Path -ne $listenerCanonical.Path -or $singleListener.Sha256 -ne $listenerHash){throw "single canonical loopback listener was rejected"}
  $script:listenerRows=@([pscustomobject]@{LocalAddress="127.0.0.1";OwningProcess=7001},[pscustomobject]@{LocalAddress="::1";OwningProcess=7001});$dualStackListener=Get-LoopbackCatDeskListener -Port 43123 -Canonical $listenerCanonical;if($dualStackListener.Pid -ne 7001 -or -not $dualStackListener.MatchesCanonical){throw "same-PID dual-stack listener rows were not coalesced"}
  $script:listenerRows=@([pscustomobject]@{LocalAddress="127.0.0.1";OwningProcess=7001},[pscustomobject]@{LocalAddress="::1";OwningProcess=7002});try{$null=Get-LoopbackCatDeskListener -Port 43123 -Canonical $listenerCanonical;throw "distinct-PID listener ambiguity was accepted"}catch{if($_.Exception.Message -match "distinct-PID listener ambiguity was accepted"){throw};if($_.Exception.Message -ne "multiple local MCP listeners are ambiguous"){throw}}
  $script:listenerRows=@([pscustomobject]@{LocalAddress="127.0.0.1";OwningProcess=7001},[pscustomobject]@{LocalAddress="::1";OwningProcess=7001},[pscustomobject]@{LocalAddress="127.0.0.1";OwningProcess=7001});try{$null=Get-LoopbackCatDeskListener -Port 43123 -Canonical $listenerCanonical;throw "three listener rows were accepted"}catch{if($_.Exception.Message -match "three listener rows were accepted"){throw};if($_.Exception.Message -ne "multiple local MCP listeners are ambiguous"){throw}}
  # T-0317: daemon discovery must distinguish the fixed daemon token from the
  # GUI mode and must never treat a same-name binary at another path as canonical.
  $foreignDaemonBinary=Join-Path $root "foreign-catdesk.exe";[IO.File]::WriteAllText($foreignDaemonBinary,"foreign-daemon")
  $daemonCreated=[DateTime]::Parse('2026-09-07T00:00:00Z').ToUniversalTime();$script:daemonRows=@([pscustomobject]@{ProcessId=7101;ExecutablePath=$listenerBinary;CommandLine="`"$listenerBinary`" --catdesk-daemon";CreationDate=$daemonCreated},[pscustomobject]@{ProcessId=7102;ExecutablePath=$listenerBinary;CommandLine="`"$listenerBinary`" --catdesk-binagotchy-gui";CreationDate=$daemonCreated},[pscustomobject]@{ProcessId=7103;ExecutablePath=$foreignDaemonBinary;CommandLine="`"$foreignDaemonBinary`" --catdesk-daemon";CreationDate=$daemonCreated})
  function Get-CimInstance { param($ClassName,$Filter,$ErrorAction) $script:daemonRows }
  $daemonCandidates=@(Get-CatDeskDaemonProcessCandidates -Canonical $listenerCanonical);if($daemonCandidates.Count -ne 2 -or $daemonCandidates[0].Pid -ne 7101 -or -not $daemonCandidates[0].MatchesCanonical -or $daemonCandidates[1].Pid -ne 7103 -or $daemonCandidates[1].MatchesCanonical){throw "daemon process attribution did not preserve canonical path/token boundaries"}
  $script:daemonRows=@(1..65|ForEach-Object{[pscustomobject]@{ProcessId=(7200+$_);ExecutablePath=$listenerBinary;CommandLine="`"$listenerBinary`" --catdesk-daemon";CreationDate=$daemonCreated}})
  try{$null=Get-CatDeskDaemonProcessCandidates -Canonical $listenerCanonical;throw 'over-bound relevant CatDesk daemon rows were silently accepted'}catch{if($_.Exception.Message -match 'silently accepted'){throw};if($_.Exception.Message -ne 'too many CatDesk process rows are ambiguous'){throw}}
  Remove-Item Function:\Get-CimInstance -ErrorAction SilentlyContinue
  Remove-Item Function:\Get-NetTCPConnection -ErrorAction SilentlyContinue;Remove-Item Function:\Get-Process -ErrorAction SilentlyContinue
  $script:BootstrapSeams["Listener"]={param($port,$canonical)[pscustomobject]@{Pid=1;MatchesCanonical=$true}}
  $script:BootstrapSeams["LocalMcpHttp"]={param($uri,$json)if($uri -notmatch [regex]::Escape("/$route/mcp")){return [pscustomobject]@{StatusCode=404;Content=""}};if($json -match 'initialize'){return [pscustomobject]@{StatusCode=200;Content='{ "result": { "serverInfo": { "name": "CatDesk" } } }'}};[pscustomobject]@{StatusCode=200;Content='{ "result": { "tools": [{"name":"catdesk_instruction"},{"name":"delegated_run_list"}] } }'}}
  if(-not(Test-LocalMcpReadiness -LocalMcp $local -Canonical ([pscustomobject]@{}))){throw "route-scoped MCP initialize/tools check rejected"}
  # T-0329 launch/readiness handoff: when bootstrap itself launched the daemon,
  # canonical equivalence is not enough. The listener must be the exact pinned
  # child process instance from this invocation.
  $expectedLaunchTime=[DateTime]::Parse('2026-09-07T00:00:00Z').ToUniversalTime();$expectedLaunch=[pscustomobject]@{Id=7001;Handle=[IntPtr]3;StartTime=$expectedLaunchTime;Path=$listenerBinary}
  $script:BootstrapSeams["Listener"]={param($port,$canonical)[pscustomobject]@{Pid=7002;CreationTimeUtc=$expectedLaunchTime.ToString('o');Path=$listenerCanonical.Path;Sha256=$listenerHash;MatchesCanonical=$true}}
  if(Test-LocalMcpReadiness -LocalMcp $local -Canonical $listenerCanonical -ExpectedDaemonProcess $expectedLaunch){throw "raced-in canonical listener was accepted as the launched daemon"}
  $script:BootstrapSeams["Listener"]={param($port,$canonical)[pscustomobject]@{Pid=7001;CreationTimeUtc=$expectedLaunchTime.ToString('o');Path=$listenerCanonical.Path;Sha256=$listenerHash;MatchesCanonical=$true}}
  if(-not(Test-LocalMcpReadiness -LocalMcp $local -Canonical $listenerCanonical -ExpectedDaemonProcess $expectedLaunch)){throw "exact launched daemon listener was rejected"}
  $script:BootstrapSeams["Listener"]={param($port,$canonical)[pscustomobject]@{Pid=1;MatchesCanonical=$true}}
  if(Test-LocalMcpReadiness -LocalMcp ([pscustomobject]@{Port=$local.Port;Uri="http://127.0.0.1:$($local.Port)/"}) -Canonical ([pscustomobject]@{})){throw "root path satisfied MCP readiness"}
  $script:BootstrapSeams["LocalMcpHttp"]={param($uri,$json)if($json -match 'initialize'){[pscustomobject]@{StatusCode=200;Content='{ "result": { "serverInfo": {} } }'}}else{[pscustomobject]@{StatusCode=200;Content='{ "result": { "tools": [{"name":"catdesk_instruction"}] } }'}}}
  if(Test-LocalMcpReadiness -LocalMcp $local -Canonical ([pscustomobject]@{})){throw "missing required MCP tool accepted"}
  $largeToolCatalog='{ "result": { "tools": [{"name":"catdesk_instruction"},{"name":"delegated_run_list"}], "padding":"'+('x'*172000)+'" } }'
  $script:BootstrapSeams["LocalMcpHttp"]={param($uri,$json)if($json -match 'initialize'){[pscustomobject]@{StatusCode=200;Content='{ "result": { "serverInfo": {} } }'}}else{[pscustomobject]@{StatusCode=200;Content=$largeToolCatalog}}}
  if(-not(Test-LocalMcpReadiness -LocalMcp $local -Canonical ([pscustomobject]@{}))){throw "large healthy MCP tool catalog was rejected"}
  $script:BootstrapSeams["LocalMcpHttp"]={param($uri,$json)throw "The operation has timed out"};$localTimeout=Get-LocalMcpReadiness -LocalMcp $local -Canonical ([pscustomobject]@{});if($localTimeout.Ready -or $localTimeout.Gate -ne 'LOCAL_MCP_RESPONSE_TIMEOUT'){throw "local MCP response timeout was not classified distinctly"}
  $script:BootstrapSeams.Remove("LocalMcpHttp")
  $script:runtimeCalls=0;$script:BootstrapSeams["RuntimeStatus"]={param($r,$t)$script:runtimeCalls++;if($script:runtimeCalls -eq 1){throw "transient unavailable"};[pscustomobject]@{processRunning=$true;healthOk=$true;isReady=$true;healthUrl="http://127.0.0.1:4411"}}
  $script:BootstrapSeams["RuntimeHttp"]={param($uri)[pscustomobject]@{StatusCode=200}}
  $transient=Get-OfficialRuntimeVerification $root 5;if($transient.Verified -or $transient.Gate -ne 'RUNTIME_STATUS_TRANSIENT'){throw "transient status failure was not classified"};if(-not(Test-OfficialRuntimeVerified $root 5)){throw "normalized runtime fields rejected"}
  $script:BootstrapSeams["RuntimeHttp"]={param($uri)if($uri -match 'readyz$'){[pscustomobject]@{StatusCode=503}}else{[pscustomobject]@{StatusCode=200}}};if(Test-OfficialRuntimeVerified $root 5){throw "readyz failure accepted"}
  $readyz=Get-OfficialRuntimeVerification $root 5;if($readyz.Gate -ne 'RUNTIME_READYZ_FAILED'){throw "readyz failure gate was not retained"}
  $script:BootstrapSeams["RuntimeHttp"]={param($uri)if($uri -match 'healthz$'){[pscustomobject]@{StatusCode=503}}else{[pscustomobject]@{StatusCode=200}}};$healthz=Get-OfficialRuntimeVerification $root 5;if($healthz.Gate -ne 'RUNTIME_HEALTHZ_FAILED'){throw "healthz failure gate was not retained"}
  $script:BootstrapSeams["RuntimeStatus"]={param($r,$t)throw 'official runtime command exceeded bounded timeout and was killed'};$timeout=Get-OfficialRuntimeVerification $root 5;if($timeout.Gate -ne 'RUNTIME_STATUS_TIMEOUT'){throw "runtime timeout was not classified"}
  $script:BootstrapSeams["RuntimeStatus"]={param($r,$t)throw 'official runtime command output exceeded bounded capture'};$oversized=Get-OfficialRuntimeVerification $root 5;if($oversized.Gate -ne 'RUNTIME_STATUS_OVERSIZED'){throw "runtime output overflow was not classified"}
  $script:BootstrapSeams["RuntimeStatus"]={param($r,$t)throw 'Conversion from JSON failed'};$malformed=Get-OfficialRuntimeVerification $root 5;if($malformed.Gate -ne 'RUNTIME_STATUS_INVALID'){throw "malformed runtime status was not classified"}
  $script:BootstrapSeams["RuntimeStatus"]={param($r,$t)[pscustomobject]@{running=$true;healthy=$true;ready=$false}};$notReady=Get-OfficialRuntimeVerification $root 5;if($notReady.Gate -ne 'RUNTIME_STATUS_NOT_READY'){throw "negative runtime status was not classified"}
  $script:BootstrapSeams["RuntimeHttp"]={param($uri)[pscustomobject]@{StatusCode=200}};$script:runtimeCalls=0;$script:BootstrapSeams["RuntimeStatus"]={param($r,$t)$script:runtimeCalls++;if($script:runtimeCalls -lt 2){throw "transient"};[pscustomobject]@{running=$true;healthy=$true;ready=$true;health_url="http://127.0.0.1:4411"}};$script:BootstrapSeams["LocalMcp"]={param($endpoint,$canonical)$true};Wait-FullStackReadiness $root $local 5 ([pscustomobject]@{})|Out-Null
  $script:localPolls=0;$script:runtimePolls=0;$script:BootstrapSeams["LocalMcp"]={param($endpoint,$canonical)$script:localPolls++;($script:localPolls -ge 3)};$script:BootstrapSeams["Runtime"]={param($r,$t)$script:runtimePolls++;($script:runtimePolls -ge 2)};Wait-FullStackReadiness $root $local 2 ([pscustomobject]@{}) "team.local" "client" 5|Out-Null;if($script:localPolls -lt 3 -or $script:runtimePolls -lt 3){throw "delayed convergence did not poll both gates"}
  $script:BootstrapSeams["LocalMcp"]={param($endpoint,$canonical)$false};$script:BootstrapSeams["Runtime"]={param($r,$t)$true};try{Wait-FullStackReadiness $root $local 1 ([pscustomobject]@{}) "team.local" "client" 5;throw "timeout accepted pending local MCP"}catch{if($_.Exception.Message -match "timeout accepted"){throw};if($_.Exception.Message -notmatch "local_mcp=LOCAL_MCP_RESPONSE_UNAVAILABLE; official_runtime=READY"){throw "timeout diagnostics were not redacted per gate"}}
  if((Get-RedactedReadinessFailureGate -Message 'full stack did not reach verified readiness; local_mcp=LOCAL_MCP_RESPONSE_UNAVAILABLE; official_runtime=READY') -ne 'LOCAL_MCP_RESPONSE_UNAVAILABLE'){throw 'local MCP failure was masked by runtime READY'}
  $script:BootstrapSeams.Remove("Runtime")
  [IO.File]::WriteAllText($config,($body+"`nruntime_alias = `"team.local`""),[Text.UTF8Encoding]::new($false));if((Get-ConfiguredRuntimeAlias $config) -ne "team.local"){throw "configured runtime alias rejected"}
  $health=Join-Path $root "health";New-Item -ItemType Directory -Path $health|Out-Null;foreach($name in @("team.local.health-url","team.local.health_url","team.local.url")){$healthFile=Join-Path $health $name;[IO.File]::WriteAllText($healthFile,"http://127.0.0.1:4412`n");if((Get-AuthoritativeRuntimeBase ([pscustomobject]@{healthUrlFile=$healthFile}) "team.local") -ne "http://127.0.0.1:4412"){throw "approved alias health file rejected"}}
  $outside=Join-Path $root "team.local.url";[IO.File]::WriteAllText($outside,"http://127.0.0.1:4412`n");try{$null=Get-AuthoritativeRuntimeBase ([pscustomobject]@{healthUrlFile=$outside}) "team.local";throw "unscoped alias URL accepted"}catch{if($_.Exception.Message -match "unscoped alias URL accepted"){throw}}
  $release=Join-Path $root "target\release";New-Item -ItemType Directory -Path $release -Force|Out-Null;$binary=Join-Path $release "catdesk.exe";[IO.File]::WriteAllText($binary,"synthetic");$hash=(Get-FixtureHash $binary -Algorithm SHA256).Hash.ToLowerInvariant();$manifest="$binary.sha256";[IO.File]::WriteAllText($manifest,"$hash`n")
  if((Get-CanonicalCatDeskIdentity $root "" $manifest).Sha256 -ne $hash){throw "valid release manifest rejected"};Remove-Item -LiteralPath $manifest -Force;try{$null=Get-CanonicalCatDeskIdentity $root "" $manifest;throw "missing manifest accepted"}catch{if($_.Exception.Message -match "missing manifest accepted"){throw}};[IO.File]::WriteAllText($manifest,"bad");try{$null=Get-CanonicalCatDeskIdentity $root "" $manifest;throw "malformed manifest accepted"}catch{if($_.Exception.Message -match "malformed manifest accepted"){throw}};[IO.File]::WriteAllText($manifest,('0'*64));try{$null=Get-CanonicalCatDeskIdentity $root "" $manifest;throw "mismatched manifest accepted"}catch{if($_.Exception.Message -match "mismatched manifest accepted"){throw}}
  # T-0154 persistent reviewed-release recovery fixtures. The first snapshot is
  # seeded only through the explicit promotion-authority helper call below.
  [IO.File]::WriteAllText($manifest,"$hash`n");$canonicalPair=Get-CatDeskCanonicalPairEvidence $root;$lkg1=Save-CatDeskLastKnownGoodRelease -Root $root -Canonical $canonicalPair;if($lkg1.Hash -ne $hash -or $lkg1.Generation -ne 1){throw "first reviewed LKG snapshot was not persisted"}
  $operationalRoot=Join-Path $root 'operational-lkg';$operationalRelease=Join-Path $operationalRoot 'target\release';New-Item -ItemType Directory -Path $operationalRelease -Force|Out-Null;$operationalBinary=Join-Path $operationalRelease 'catdesk.exe';[IO.File]::WriteAllText($operationalBinary,'operational-verified');$operationalHash=(Get-FixtureHash $operationalBinary -Algorithm SHA256).Hash.ToLowerInvariant();[IO.File]::WriteAllText("$operationalBinary.sha256","$operationalHash`n");$operationalPair=Get-CatDeskCanonicalPairEvidence $operationalRoot;try{$null=Save-CatDeskLastKnownGoodRelease -Root $operationalRoot -Canonical $operationalPair -Source 'operational_verified';throw 'operational health minted LKG authority'}catch{if($_.Exception.Message -match 'operational health minted LKG authority'){throw};if($_.Exception.Message -ne 'LKG_AUTHORITY_MISSING'){throw}};$operationalPointer=Join-Path $operationalRoot '.catdesk\release-recovery\current.json';if(Test-Path -LiteralPath $operationalPointer){throw 'operational health wrote an LKG pointer without reviewed authority'};$reviewedOperationalLkg=Save-CatDeskLastKnownGoodRelease -Root $operationalRoot -Canonical $operationalPair;$reusedOperationalLkg=Save-CatDeskLastKnownGoodRelease -Root $operationalRoot -Canonical $operationalPair -Source 'operational_verified';$operationalManifest=[IO.File]::ReadAllText($reusedOperationalLkg.Metadata)|ConvertFrom-Json;if($reusedOperationalLkg.Hash -ne $operationalHash -or $reusedOperationalLkg.Generation -ne $reviewedOperationalLkg.Generation -or [string]$operationalManifest.source -ne 'reviewed_promotion'){throw 'operational health did not preserve matching reviewed LKG authority'};[IO.File]::WriteAllText($operationalBinary,'broken-operational');[IO.File]::WriteAllText("$operationalBinary.sha256",(('f'*64)+"`n"));$operationalRestore=Restore-CatDeskCanonicalFromLastKnownGood -Root $operationalRoot;if(-not $operationalRestore.RestoredBinary -or -not $operationalRestore.RestoredManifest -or (Get-CatDeskCanonicalPairEvidence $operationalRoot).Hash -ne $operationalHash){throw 'reviewed LKG snapshot did not restore the canonical pair after operational reuse'};try{$null=Save-CatDeskLastKnownGoodRelease -Root $operationalRoot -Canonical $operationalPair -Source 'untrusted';throw 'invalid LKG source was accepted'}catch{if($_.Exception.Message -match 'invalid LKG source was accepted'){throw}}
  # T-0322 legacy compatibility: runtime health snapshots produced by older
  # builds are not rollback authority, even when a durable pointer names them.
  $legacyOperationalRoot=Join-Path $root 'legacy-operational-authority';$legacyRecovery=Join-Path $legacyOperationalRoot '.catdesk\release-recovery';$legacyOperationalSlot=Join-Path $legacyRecovery 'slot-a';New-Item -ItemType Directory -Path $legacyOperationalSlot -Force|Out-Null;$legacyOperationalBinary=Join-Path $legacyOperationalSlot 'catdesk.exe';[IO.File]::WriteAllText($legacyOperationalBinary,'legacy-operational');$legacyOperationalHash=(Get-FixtureHash $legacyOperationalBinary -Algorithm SHA256).Hash.ToLowerInvariant();[IO.File]::WriteAllText((Join-Path $legacyOperationalSlot 'catdesk.exe.sha256'),"$legacyOperationalHash`n");@{schemaVersion=1;generation=2;sha256=$legacyOperationalHash;source='operational_verified';capturedAtUtc=[DateTime]::UtcNow.ToString('o')}|ConvertTo-Json -Compress|Set-Content -LiteralPath (Join-Path $legacyOperationalSlot 'manifest.json') -Encoding utf8;@{schemaVersion=1;slot='slot-a';generation=2;sha256=$legacyOperationalHash}|ConvertTo-Json -Compress|Set-Content -LiteralPath (Join-Path $legacyRecovery 'current.json') -Encoding utf8
  try{$null=Read-CatDeskLkgSlot -Root $legacyOperationalRoot -Slot 'slot-a';throw 'legacy operational LKG source was accepted'}catch{if($_.Exception.Message -match 'legacy operational LKG source was accepted'){throw};if($_.Exception.Message -ne 'release recovery source is not authoritative'){throw}};try{$null=Get-CatDeskLastKnownGoodRelease $legacyOperationalRoot;throw 'legacy operational LKG retained rollback authority'}catch{if($_.Exception.Message -match 'retained rollback authority'){throw};if($_.Exception.Message -ne 'no trusted release recovery snapshot is available'){throw}}
  if((Get-CatDeskLkgAuthorityFailure $legacyOperationalRoot) -ne 'LKG_AUTHORITY_MISSING'){throw 'legacy operational-only escrow was misclassified as damaged reviewed authority'}
  $reviewedFallbackSlot=Join-Path $legacyRecovery 'slot-b';New-Item -ItemType Directory -Path $reviewedFallbackSlot -Force|Out-Null;$reviewedFallbackBinary=Join-Path $reviewedFallbackSlot 'catdesk.exe';[IO.File]::WriteAllText($reviewedFallbackBinary,'reviewed-fallback');$reviewedFallbackHash=(Get-FixtureHash $reviewedFallbackBinary -Algorithm SHA256).Hash.ToLowerInvariant();[IO.File]::WriteAllText((Join-Path $reviewedFallbackSlot 'catdesk.exe.sha256'),"$reviewedFallbackHash`n");@{schemaVersion=1;generation=1;sha256=$reviewedFallbackHash;source='reviewed_promotion';capturedAtUtc=[DateTime]::UtcNow.ToString('o')}|ConvertTo-Json -Compress|Set-Content -LiteralPath (Join-Path $reviewedFallbackSlot 'manifest.json') -Encoding utf8;$reviewedFallback=Get-CatDeskLastKnownGoodRelease $legacyOperationalRoot;if($reviewedFallback.Slot -ne 'slot-b' -or $reviewedFallback.Generation -ne 1 -or $reviewedFallback.Hash -ne $reviewedFallbackHash){throw 'legacy operational pointer displaced reviewed rollback authority'}
  [IO.File]::WriteAllText($manifest,(('f'*64)+"`n"));$sidecarRepair=Restore-CatDeskCanonicalFromLastKnownGood $root;if($sidecarRepair.RestoredBinary -or -not $sidecarRepair.RestoredManifest -or (Get-CatDeskCanonicalPairEvidence $root).Hash -ne $hash){throw "sidecar-only split brain was not self-healed from LKG"}
  [IO.File]::WriteAllText($binary,"corrupt-binary");$binaryRepair=Restore-CatDeskCanonicalFromLastKnownGood $root;if(-not $binaryRepair.RestoredBinary -or $binaryRepair.RestoredManifest -or (Get-CatDeskCanonicalPairEvidence $root).Hash -ne $hash){throw "binary-only split brain was not self-healed from LKG"}
  [IO.File]::WriteAllText($binary,"corrupt-both");[IO.File]::WriteAllText($manifest,(('e'*64)+"`n"));$pairRepair=Restore-CatDeskCanonicalFromLastKnownGood $root;if(-not $pairRepair.RestoredBinary -or -not $pairRepair.RestoredManifest -or (Get-CatDeskCanonicalPairEvidence $root).Hash -ne $hash){throw "two-sided canonical split brain was not self-healed from LKG"}
  [IO.File]::WriteAllText($binary,"synthetic-v2");$hash2=(Get-FixtureHash $binary -Algorithm SHA256).Hash.ToLowerInvariant();[IO.File]::WriteAllText($manifest,"$hash2`n");$canonicalPair2=Get-CatDeskCanonicalPairEvidence $root;$lkg2=Save-CatDeskLastKnownGoodRelease -Root $root -Canonical $canonicalPair2;if($lkg2.Hash -ne $hash2 -or $lkg2.Generation -ne 2 -or $lkg2.Slot -eq $lkg1.Slot){throw "second reviewed LKG generation did not use the inactive slot"}
  $pointer=Join-Path $root ".catdesk\release-recovery\current.json";[IO.File]::WriteAllText($pointer,"corrupt-pointer");$reconciled=Get-CatDeskLastKnownGoodRelease $root;if($reconciled.Hash -ne $hash2 -or $reconciled.Generation -ne 2){throw "corrupt LKG pointer did not reconcile to the unique highest valid generation"};$pointerRepair=Save-CatDeskLastKnownGoodRelease -Root $root -Canonical $canonicalPair2;$repairedPointer=Read-CatDeskLkgPointer $root;if($pointerRepair.Generation -ne 2 -or $repairedPointer.Generation -ne 2 -or $repairedPointer.Hash -ne $hash2 -or $repairedPointer.Slot -ne $lkg2.Slot){throw "same-hash reviewed promotion did not repair the durable LKG pointer"}
  $inactive=if($lkg2.Slot -eq 'slot-a'){'slot-b'}else{'slot-a'};$inactivePath=Join-Path $root ".catdesk\release-recovery\$inactive";Remove-Item -LiteralPath $inactivePath -Recurse -Force;New-Item -ItemType Directory -Path $inactivePath|Out-Null;[IO.File]::WriteAllText((Join-Path $inactivePath 'manifest.json'),'partial');$reconciledPartial=Get-CatDeskLastKnownGoodRelease $root;if($reconciledPartial.Hash -ne $hash2){throw "incomplete inactive LKG slot displaced the valid generation"}
  $noLkgRoot=Join-Path $root 'no-lkg';New-Item -ItemType Directory -Path $noLkgRoot|Out-Null;try{$null=Get-CatDeskLastKnownGoodRelease $noLkgRoot;throw "missing LKG authority was accepted"}catch{if($_.Exception.Message -match "missing LKG authority was accepted"){throw}}
  # T-0159: native reload receipts, health/process continuity, and review
  # bundles are not promotion approval.  Only the exact durable promotion
  # completion record may migrate a pre-LKG installation.
  $legacyRoot=Join-Path $root 'legacy-reviewed';$legacyRelease=Join-Path $legacyRoot 'target\release';New-Item -ItemType Directory -Path $legacyRelease -Force|Out-Null;$legacyBinary=Join-Path $legacyRelease 'catdesk.exe';[IO.File]::WriteAllText($legacyBinary,'legacy-reviewed');$legacyHash=(Get-FixtureHash $legacyBinary -Algorithm SHA256).Hash.ToLowerInvariant();[IO.File]::WriteAllText("$legacyBinary.sha256","$legacyHash`n");$legacyPair=Get-CatDeskCanonicalPairEvidence $legacyRoot
  $reloadDir=Join-Path $legacyRoot '.catdesk\restart-handoff';New-Item -ItemType Directory -Path $reloadDir -Force|Out-Null;@{schemaVersion=1;status='REPLACEMENT_READY_PENDING_TRANSPORT_RECONNECT';completedAtUnix=[DateTimeOffset]::UtcNow.ToUnixTimeSeconds();oldPid=11;newPid=12;port=3200;replacementSha256=$legacyHash;stage='complete';rollbackAttempted=$false;rollbackReady=$false}|ConvertTo-Json -Compress|Set-Content -LiteralPath (Join-Path $reloadDir 'latest.json') -Encoding utf8
  try{$null=Initialize-CatDeskLastKnownGoodFromReviewedPromotion -Root $legacyRoot -Canonical $legacyPair;throw 'native reload receipt minted LKG authority'}catch{if($_.Exception.Message -match 'native reload receipt minted LKG authority'){throw}};if(Test-Path -LiteralPath (Join-Path $legacyRoot '.catdesk\release-recovery\current.json')){throw 'native reload receipt wrote LKG pointer'}
  $bundle=Join-Path $legacyRoot 'docs\orchestrator\review_bundles\review.md';New-Item -ItemType Directory -Path (Split-Path $bundle) -Force|Out-Null;[IO.File]::WriteAllText($bundle,'review');try{$null=Initialize-CatDeskLastKnownGoodFromReviewedPromotion -Root $legacyRoot -Canonical $legacyPair;throw 'review bundle minted LKG authority'}catch{if($_.Exception.Message -match 'review bundle minted LKG authority'){throw}}
  $authorityDir=Join-Path $legacyRoot '.catdesk\promotion-recovery';New-Item -ItemType Directory -Path $authorityDir -Force|Out-Null;@{schemaVersion=1;transactionId='0123456789abcdef0123456789abcdef';authorizationId='fedcba9876543210fedcba9876543210';stage='CANONICAL_HANDOFF_PROVEN';candidateHash=$legacyHash;canonicalRelativePath='target\release\catdesk.exe';canonicalSha256=$legacyHash}|ConvertTo-Json -Compress|Set-Content -LiteralPath (Join-Path $authorityDir 'reviewed-promotion.json') -Encoding utf8;$legacyLkg=Initialize-CatDeskLastKnownGoodFromReviewedPromotion -Root $legacyRoot -Canonical $legacyPair;if($legacyLkg.Hash -ne $legacyHash -or -not(Test-Path -LiteralPath (Join-Path $legacyRoot '.catdesk\release-recovery\current.json'))){throw 'exact reviewed promotion authority did not migrate legacy LKG escrow'}
  $wrongAuthorityRoot=Join-Path $root 'legacy-wrong-authority';$wrongRelease=Join-Path $wrongAuthorityRoot 'target\release';New-Item -ItemType Directory -Path $wrongRelease -Force|Out-Null;$wrongBinary=Join-Path $wrongRelease 'catdesk.exe';[IO.File]::WriteAllText($wrongBinary,'unproven');$wrongHash=(Get-FixtureHash $wrongBinary -Algorithm SHA256).Hash.ToLowerInvariant();[IO.File]::WriteAllText("$wrongBinary.sha256","$wrongHash`n");$wrongAuthorityDir=Join-Path $wrongAuthorityRoot '.catdesk\promotion-recovery';New-Item -ItemType Directory -Path $wrongAuthorityDir -Force|Out-Null;@{schemaVersion=1;transactionId='fedcba9876543210fedcba9876543210';stage='CANONICAL_HANDOFF_PROVEN';candidateHash=('0'*64);canonicalRelativePath='target\release\catdesk.exe';canonicalSha256=('0'*64)}|ConvertTo-Json -Compress|Set-Content -LiteralPath (Join-Path $wrongAuthorityDir 'reviewed-promotion.json') -Encoding utf8;try{$null=Initialize-CatDeskLastKnownGoodFromReviewedPromotion -Root $wrongAuthorityRoot -Canonical (Get-CatDeskCanonicalPairEvidence $wrongAuthorityRoot);throw 'wrong promotion authority minted LKG escrow'}catch{if($_.Exception.Message -match 'wrong promotion authority minted LKG escrow'){throw}};if(Test-Path -LiteralPath (Join-Path $wrongAuthorityRoot '.catdesk\release-recovery\current.json')){throw 'wrong promotion authority wrote LKG pointer'}
  [IO.File]::WriteAllText((Join-Path $wrongAuthorityDir 'reviewed-promotion.json'),'{"schemaVersion":1}');try{$null=Initialize-CatDeskLastKnownGoodFromReviewedPromotion -Root $wrongAuthorityRoot -Canonical (Get-CatDeskCanonicalPairEvidence $wrongAuthorityRoot);throw 'malformed promotion authority minted LKG escrow'}catch{if($_.Exception.Message -match 'malformed promotion authority minted LKG escrow'){throw}};if(Test-Path -LiteralPath (Join-Path $wrongAuthorityRoot '.catdesk\release-recovery\current.json')){throw 'malformed promotion authority wrote LKG pointer'}
  $sizeRoot=Join-Path $root 'size-root';$sizeSlot=Join-Path $sizeRoot '.catdesk\release-recovery\slot-a';New-Item -ItemType Directory -Path $sizeSlot -Force|Out-Null;$emptyBinary=Join-Path $sizeSlot 'catdesk.exe';[IO.File]::WriteAllBytes($emptyBinary,[byte[]]@());$emptyHash=(Get-FixtureHash $emptyBinary -Algorithm SHA256).Hash.ToLowerInvariant();[IO.File]::WriteAllText((Join-Path $sizeSlot 'catdesk.exe.sha256'),"$emptyHash`n");@{schemaVersion=1;generation=1;sha256=$emptyHash;source='reviewed_promotion';capturedAtUtc=[DateTime]::UtcNow.ToString('o')}|ConvertTo-Json -Compress|Set-Content -LiteralPath (Join-Path $sizeSlot 'manifest.json') -Encoding utf8;try{$null=Read-CatDeskLkgSlot -Root $sizeRoot -Slot 'slot-a';throw "zero-byte LKG binary was accepted"}catch{if($_.Exception.Message -match "zero-byte LKG binary was accepted"){throw}}
  $reparseRoot=Join-Path $root 'reparse-root';$reparseTarget=Join-Path $root 'reparse-target';New-Item -ItemType Directory -Path $reparseRoot,$reparseTarget -Force|Out-Null;$controlJunction=Join-Path $reparseRoot '.catdesk';New-Item -ItemType Junction -Path $controlJunction -Target $reparseTarget|Out-Null;try{$null=Get-CatDeskReleaseRecoveryDirectory $reparseRoot;throw "reparse .catdesk recovery parent was accepted"}catch{if($_.Exception.Message -match "reparse .catdesk recovery parent was accepted"){throw}}finally{[IO.Directory]::Delete($controlJunction)}
  # Restore the valid v2 pointer so later fake orchestration tests begin from a
  # deterministic fixture even though they replace canonical identity calls.
  $pointerValue=[ordered]@{schemaVersion=1;slot=$lkg2.Slot;generation=$lkg2.Generation;sha256=$lkg2.Hash}|ConvertTo-Json -Compress;Write-CatDeskAtomicUtf8 -Path $pointer -Text $pointerValue
  [IO.File]::WriteAllText($manifest,(('d'*64)+"`n"));$engineRepair=Repair-CanonicalReleaseForRecovery -Root $root -Config $config -ExpectedHash "";if($engineRepair.Source -ne 'LAST_KNOWN_GOOD' -or $engineRepair.RestoredBinary -or -not $engineRepair.RestoredManifest -or (Get-CatDeskCanonicalPairEvidence $root).Hash -ne $hash2){throw "recovery engine did not self-heal the exact sidecar-only incident shape"}
  [IO.File]::WriteAllText($manifest,(('d'*64)+"`n"));$assessment=Get-CanonicalReleaseRecoveryAssessment -Root $root -ExpectedHash "";if($assessment.State -ne 'RECOVERY_READY' -or $assessment.RecoverySource -ne 'LAST_KNOWN_GOOD' -or (Get-Content -LiteralPath $manifest -Raw) -notmatch ('d'*64)){throw 'read-only recovery assessment changed the broken canonical pair'}
  function Invoke-InterruptedPromotionPairRecovery { param($Root) throw 'fixture interrupted promotion recovery was not proven' }
  $interruptedFallback=Repair-CanonicalReleaseForRecovery -Root $root -Config $config -ExpectedHash "";if($interruptedFallback.Source -ne 'LAST_KNOWN_GOOD' -or -not $interruptedFallback.RestoredManifest -or (Get-CatDeskCanonicalPairEvidence $root).Hash -ne $hash2){throw 'unproven interrupted promotion blocked exact LKG recovery'}
  $repeatFallback=Repair-CanonicalReleaseForRecovery -Root $root -Config $config -ExpectedHash "";if($repeatFallback.Source -ne 'LAST_KNOWN_GOOD' -or $repeatFallback.RestoredBinary -or $repeatFallback.RestoredManifest -or (Get-CatDeskCanonicalPairEvidence $root).Hash -ne $hash2){throw 'repeated exact LKG recovery was not idempotent'}
  try{$null=Repair-CanonicalReleaseForRecovery -Root $noLkgRoot -Config $config -ExpectedHash "";throw "recovery engine accepted missing trusted authority"}catch{if($_.Exception.Message -match "accepted missing trusted authority"){throw}}
  $missingAssessment=Get-CanonicalReleaseRecoveryAssessment -Root $noLkgRoot -ExpectedHash "";if($missingAssessment.State -ne 'LKG_AUTHORITY_MISSING'){throw 'missing recovery authority was not classified fail-closed'}
  $ambiguousRoot=Join-Path $root 'ambiguous-lkg';$ambiguousRelease=Join-Path $ambiguousRoot 'target\release';New-Item -ItemType Directory -Path $ambiguousRelease -Force|Out-Null;$ambiguousBinary=Join-Path $ambiguousRelease 'catdesk.exe';[IO.File]::WriteAllText($ambiguousBinary,'ambiguous-reviewed');$ambiguousHash=(Get-FixtureHash $ambiguousBinary -Algorithm SHA256).Hash.ToLowerInvariant();[IO.File]::WriteAllText("$ambiguousBinary.sha256","$ambiguousHash`n");$ambiguousPair=Get-CatDeskCanonicalPairEvidence $ambiguousRoot;$ambiguousLkg=Save-CatDeskLastKnownGoodRelease -Root $ambiguousRoot -Canonical $ambiguousPair;$ambiguousOther=if($ambiguousLkg.Slot -eq 'slot-a'){'slot-b'}else{'slot-a'};$ambiguousRecovery=Join-Path $ambiguousRoot '.catdesk\release-recovery';Copy-Item -LiteralPath (Join-Path $ambiguousRecovery $ambiguousLkg.Slot) -Destination (Join-Path $ambiguousRecovery $ambiguousOther) -Recurse -Force;Remove-Item -LiteralPath (Join-Path $ambiguousRecovery 'current.json') -Force;$ambiguousAssessment=Get-CanonicalReleaseRecoveryAssessment -Root $ambiguousRoot -ExpectedHash "";if($ambiguousAssessment.State -ne 'LKG_AUTHORITY_AMBIGUOUS_OR_DAMAGED'){throw 'ambiguous recovery authority was not classified fail-closed'}
  # Fake every side-effect boundary to exercise idempotent daemon orchestration.
  function New-FakeListener { param([Alias('Pid')][int]$ProcessId,[bool]$MatchesCanonical,[string]$CreationTimeUtc='2026-09-07T00:00:00.0000000Z',[string]$Path='C:\\observed\\catdesk.exe',[string]$Sha256=('a'*64))[pscustomobject]@{Pid=$ProcessId;CreationTimeUtc=$CreationTimeUtc;Path=$Path;Sha256=$Sha256;MatchesCanonical=$MatchesCanonical} }
  $script:actions=[Collections.Generic.List[string]]::new();$script:fakeMode="official_runtime";$script:fakeListener=New-FakeListener -Pid 11 -MatchesCanonical $true
  $script:BootstrapSeams["DaemonProcesses"]={param($canonical) @()}
  $script:BootstrapSeams["DaemonProcessInstance"]={param($canonical,$candidate) $p=[pscustomobject]@{Id=[int]$candidate.Pid};$p|Add-Member -MemberType ScriptMethod -Name Kill -Value {[void]$script:actions.Add("stop:$($this.Id)")};$p|Add-Member -MemberType ScriptMethod -Name WaitForExit -Value {param($milliseconds)$true};$p}
  $script:BootstrapSeams["ListenerProcessInstance"]={param($candidate) $p=[pscustomobject]@{Id=[int]$candidate.Pid};$p|Add-Member -MemberType ScriptMethod -Name Kill -Value {[void]$script:actions.Add("stop:$($this.Id)");if($null -ne $script:fakeListener -and [int]$script:fakeListener.Pid -eq [int]$this.Id){$script:fakeListener=$null}};$p|Add-Member -MemberType ScriptMethod -Name WaitForExit -Value {param($milliseconds)$true};$p};$script:goodListenerProcessInstanceSeam=$script:BootstrapSeams["ListenerProcessInstance"]
  function Get-CanonicalCatDeskIdentity { param($Root,$ExpectedHash,$FingerprintPath)[pscustomobject]@{Path="C:\\canonical\\catdesk.exe";Sha256="abc"} }
  function Get-ConfiguredLocalMcp { param($Path)[pscustomobject]@{Port=43123;Uri="http://127.0.0.1:43123/redacted/mcp"} }
  function Get-ConfiguredRuntimeAlias { param($Path)"test-alias" }
  function Find-TunnelClient { param($ExplicitPath)"C:\\synthetic\\tunnel-client.exe" }
  function Test-WakeBridgeRuntime { param($Root)$script:wakeReady }
  function Invoke-WakeBridgeRuntimeRepair { param($Root)[void]$script:actions.Add("wake-repair");if($script:prerequisiteDelayMilliseconds -gt 0){Start-Sleep -Milliseconds $script:prerequisiteDelayMilliseconds};$script:wakeReady=$true;$script:lastPrerequisiteCompletedUtc=[DateTime]::UtcNow }
  function Read-OfficialRuntimeProcessMode { param($Path)$script:fakeMode }
  function Get-LoopbackCatDeskListener { param($Port,$Canonical)$script:fakeListener }
  function Test-CodexOnDemandPrerequisites {}
  function Stop-Process { param($Id)[void]$script:actions.Add("stop:$Id") }
  function Get-Process { param($Id)$null }
  function Invoke-OrderedOfficialRuntimeMigration { param($SetupScript,$Path)[void]$script:actions.Add("migrate");if($script:prerequisiteDelayMilliseconds -gt 0){Start-Sleep -Milliseconds $script:prerequisiteDelayMilliseconds};$script:fakeMode="official_runtime";$script:lastPrerequisiteCompletedUtc=[DateTime]::UtcNow }
  function Start-Process { param($FilePath,$ArgumentList,$WorkingDirectory,$WindowStyle,[switch]$PassThru)[void]$script:actions.Add("start:$ArgumentList");[pscustomobject]@{Id=12;Handle=[IntPtr]4} }
  function Test-OfficialRuntimeVerified { param($Root,$TimeoutSeconds,$Alias,$ClientPath)$true }
  $script:lastExpectedDaemonProcess=$null;$script:lastReadinessDeadline=$null;$script:lastPrerequisiteCompletedUtc=$null;$script:prerequisiteDelayMilliseconds=0
  function Wait-FullStackReadiness { param($Root,$LocalMcp,$TimeoutSeconds,$Canonical,$Alias,$ClientPath,$Deadline,$ExpectedDaemonProcess)$script:lastExpectedDaemonProcess=$ExpectedDaemonProcess;$script:lastReadinessDeadline=$Deadline;$true }
  function Write-RedactedStatus { param($State,$Detail,$RecoverySource='',$Gate='');if($Gate){return "{`"State`":`"$State`",`"Gate`":`"$Gate`"}"};return "{`"State`":`"$State`"}" }
  $script:BootstrapSeams["GuiInteractiveDesktop"]={ $false }
  $script:wakeReady=$true;$Workspace=$root;$ConfigPath=$config;$BuildFingerprintPath=$manifest;$ExpectedBuildSha256="";$ReadyTimeoutSeconds=5;$Mode="plan";$Execute=$false;Invoke-CanonicalStackBootstrap|Out-Null;if($script:actions.Count -ne 0){throw "healthy canonical daemon was duplicated"}
  $script:fakeListener=New-FakeListener -Pid 12 -MatchesCanonical $false;$Mode="recover";$Execute=$true;Invoke-CanonicalStackBootstrap|Out-Null;if(([string]::Join(",",$script:actions)) -ne "stop:12,start:--catdesk-daemon"){throw "mismatched daemon did not receive native reload"};if($null -eq $script:lastExpectedDaemonProcess -or [int]$script:lastExpectedDaemonProcess.Id -ne 12){throw "launched daemon process identity was not forwarded into readiness"}
  # T-0326 exact-listener-instance races: a PID that resolves to a changed
  # process instance, or a replacement listener that appears after pinning,
  # must fail before Kill/start/migration can target the replacement.
  $script:actions.Clear();$script:fakeListener=New-FakeListener -Pid 120 -MatchesCanonical $false;$script:BootstrapSeams["ListenerProcessInstance"]={param($candidate) throw "CatDesk listener process instance changed before recovery mutation"};try{Invoke-CanonicalStackBootstrap|Out-Null;throw "changed listener process instance was terminated"}catch{if($_.Exception.Message -match "was terminated"){throw};if($_.Exception.Message -ne "CatDesk listener process instance changed before recovery mutation"){throw}};if($script:actions.Count -ne 0){throw "changed listener process instance caused a mutation"}
  $script:actions.Clear();$script:fakeListener=New-FakeListener -Pid 121 -MatchesCanonical $false;$script:BootstrapSeams["ListenerProcessInstance"]={param($candidate)$script:fakeListener=New-FakeListener -Pid 122 -MatchesCanonical $false -CreationTimeUtc '2026-09-07T00:00:01.0000000Z';$p=[pscustomobject]@{Id=[int]$candidate.Pid};$p|Add-Member -MemberType ScriptMethod -Name Kill -Value {[void]$script:actions.Add("unsafe-stop:$($this.Id)")};$p|Add-Member -MemberType ScriptMethod -Name WaitForExit -Value {param($milliseconds)$true};$p};try{Invoke-CanonicalStackBootstrap|Out-Null;throw "replacement listener was terminated"}catch{if($_.Exception.Message -match "was terminated"){throw};if($_.Exception.Message -ne "CatDesk listener changed before recovery mutation"){throw}};if($script:actions.Count -ne 0){throw "replacement listener caused a mutation"};$script:BootstrapSeams["ListenerProcessInstance"]=$script:goodListenerProcessInstanceSeam
  $script:actions.Clear();$script:identityAttempts=0;function Get-CanonicalCatDeskIdentity { param($Root,$ExpectedHash,$FingerprintPath)$script:identityAttempts++;if($script:identityAttempts -eq 1){throw "canonical CatDesk build fingerprint did not match"};[pscustomobject]@{Path="C:\\canonical\\catdesk.exe";Sha256="abc"} };function Repair-CanonicalReleaseForRecovery { param($Root,$Config,$ExpectedHash)[void]$script:actions.Add("pair-repair");[pscustomobject]@{Source='LAST_KNOWN_GOOD';RestoredBinary=$false;RestoredManifest=$true} };$script:fakeListener=New-FakeListener -Pid 14 -MatchesCanonical $true;$script:fakeMode="official_runtime";$Mode="recover";$Execute=$true;Invoke-CanonicalStackBootstrap|Out-Null;if(([string]::Join(",",$script:actions)) -ne "pair-repair" -or $script:identityAttempts -ne 2){throw "recover did not repair and revalidate broken canonical identity before daemon orchestration"}
  function Get-CanonicalCatDeskIdentity { param($Root,$ExpectedHash,$FingerprintPath)[pscustomobject]@{Path="C:\\canonical\\catdesk.exe";Sha256="abc"} }
  # Release repair uses the same pinned observed-listener mutation boundary even
  # when current canonical bytes are damaged and therefore cannot be required
  # to match the reviewed target hash that will replace them.
  $repairObservedPath=(Resolve-Path -LiteralPath $binary).Path;$repairObservedHash=(Get-FixtureHash -LiteralPath $binary -Algorithm SHA256).Hash.ToLowerInvariant();$script:actions.Clear();$script:fakeListener=New-FakeListener -Pid 123 -MatchesCanonical $true -Path $repairObservedPath -Sha256 $repairObservedHash;$script:BootstrapSeams["ListenerProcessInstance"]={param($candidate) throw "CatDesk listener process instance changed before recovery mutation"};try{$null=Stop-CanonicalPathCatDeskForReleaseRepair -Root $root -Config $config;throw "changed release-repair listener was terminated"}catch{if($_.Exception.Message -match "was terminated"){throw};if($_.Exception.Message -ne "CatDesk listener process instance changed before recovery mutation"){throw}};if($script:actions.Count -ne 0){throw "changed release-repair listener caused a mutation"};$script:BootstrapSeams["ListenerProcessInstance"]=$script:goodListenerProcessInstanceSeam
  $script:actions.Clear();$script:fakeListener=New-FakeListener -Pid 124 -MatchesCanonical $true -Path $repairObservedPath -Sha256 $repairObservedHash;if(-not(Stop-CanonicalPathCatDeskForReleaseRepair -Root $root -Config $config)){throw "release repair did not stop the exact pinned listener"};if(([string]::Join(",",$script:actions)) -ne "stop:124"){throw "release repair did not use the pinned process instance"}
  $script:actions.Clear();$script:fakeListener=New-FakeListener -Pid 13 -MatchesCanonical $true;$script:fakeMode="external_foreground";Invoke-CanonicalStackBootstrap|Out-Null;if(([string]::Join(",",$script:actions)) -ne "stop:13,migrate,start:--catdesk-daemon"){throw "legacy migration order was not stop-migrate-start"}
  # T-0339 one-command phase boundary: bounded prerequisite repair/migration may
  # legitimately consume longer than the final readiness timeout. They must not
  # consume that convergence budget or force a second recover invocation.
  $script:actions.Clear();$script:wakeReady=$false;$script:fakeListener=New-FakeListener -Pid 130 -MatchesCanonical $true;$script:fakeMode="external_foreground";$script:prerequisiteDelayMilliseconds=1200;$script:lastPrerequisiteCompletedUtc=$null;$script:lastReadinessDeadline=$null;Invoke-CanonicalStackBootstrap|Out-Null;$remainingAfterPrerequisites=($script:lastReadinessDeadline-$script:lastPrerequisiteCompletedUtc).TotalMilliseconds;if($remainingAfterPrerequisites -lt 4500){throw "prerequisite phases consumed the final recovery readiness budget"};if(([string]::Join(",",$script:actions)) -ne "wake-repair,stop:130,migrate,start:--catdesk-daemon"){throw "delayed prerequisites did not converge in the same recovery invocation"};$script:prerequisiteDelayMilliseconds=0
  $bootstrapNode=$ast.Find({param($n)$n -is [System.Management.Automation.Language.FunctionDefinitionAst] -and $n.Name -eq 'Invoke-CanonicalStackBootstrap'},$true);$timeoutRepairNode=$bootstrapNode.Find({param($n)$n -is [System.Management.Automation.Language.IfStatementAst] -and $n.Extent.Text -match 'LOCAL_MCP_RESPONSE_TIMEOUT' -and $n.Extent.Text -match 'Stop-CatDeskListenerProcessForRecovery'},$true);if($null -eq $timeoutRepairNode){throw 'local MCP timeout repair branch is missing'};$timeoutRepairSource=$timeoutRepairNode.Extent.Text;foreach($forbiddenTunnelMutation in @('Invoke-OrderedOfficialRuntimeMigration','setup-secure-mcp','runtimes connect','runtimes stop','runtimes delete')){if($timeoutRepairSource -match [regex]::Escape($forbiddenTunnelMutation)){throw "local MCP timeout repair acquired tunnel mutation authority: $forbiddenTunnelMutation"}}
  # T-0430 selective downstream recovery: a canonical listener whose MCP
  # request path times out may be recycled only while the externally owned
  # official runtime is independently verified healthy. The tunnel itself is
  # never a mutation target on this path.
  $script:actions.Clear();$script:fakeMode="official_runtime";$script:fakeListener=New-FakeListener -Pid 24 -MatchesCanonical $true;$script:BootstrapSeams["LocalMcp"]={param($endpoint,$canonical)[pscustomobject]@{Ready=$false;Gate='LOCAL_MCP_RESPONSE_TIMEOUT'}};$script:BootstrapSeams["Runtime"]={param($r,$t)$true};$Mode="recover";$Execute=$true;Invoke-CanonicalStackBootstrap|Out-Null;if(([string]::Join(",",$script:actions)) -ne "stop:24,start:--catdesk-daemon"){throw "healthy tunnel plus timed-out local MCP did not selectively recycle only the local daemon"}
  $script:actions.Clear();$script:fakeListener=New-FakeListener -Pid 25 -MatchesCanonical $true;$script:BootstrapSeams["Runtime"]={param($r,$t)$false};Invoke-CanonicalStackBootstrap|Out-Null;if($script:actions.Count -ne 0){throw "unverified tunnel plus timed-out local MCP caused a recovery mutation"}
  # Plan mode is read-only but must exercise the same local/runtime request
  # paths so a live listener with a dead MCP request loop cannot claim ready.
  $script:actions.Clear();$script:fakeListener=New-FakeListener -Pid 26 -MatchesCanonical $true;$script:BootstrapSeams["LocalMcp"]={param($endpoint,$canonical)[pscustomobject]@{Ready=$false;Gate='LOCAL_MCP_RESPONSE_TIMEOUT'}};$script:BootstrapSeams["Runtime"]={param($r,$t)$true};$Mode="plan";$Execute=$false;$planLocal=(Invoke-CanonicalStackBootstrap|Out-String);if($planLocal -notmatch '"State":"LOCAL_MCP_NOT_READY"' -or $planLocal -notmatch '"Gate":"LOCAL_MCP_RESPONSE_TIMEOUT"'){throw "plan mode did not surface the local MCP response timeout"};if($script:actions.Count -ne 0){throw "plan-mode local MCP timeout caused a mutation"}
  $script:actions.Clear();$script:BootstrapSeams["LocalMcp"]={param($endpoint,$canonical)$true};$script:BootstrapSeams["Runtime"]={param($r,$t)$false};$planRuntime=(Invoke-CanonicalStackBootstrap|Out-String);if($planRuntime -notmatch '"State":"OFFICIAL_RUNTIME_NOT_READY"'){throw "plan mode did not surface unverified official runtime"};if($script:actions.Count -ne 0){throw "plan-mode runtime failure caused a mutation"}
  $Mode="recover";$Execute=$true;$script:BootstrapSeams["LocalMcp"]={param($endpoint,$canonical)$true};$script:BootstrapSeams.Remove("Runtime")
  # R3 environment-inheritance convergence: all commands below are fakes.
  function Test-OfficialRuntimeVerified { param($Root,$TimeoutSeconds,$Alias,$ClientPath)[void]$script:aliases.Add($Alias);$script:runtimeResults[0] }
  function Wait-FullStackReadiness { param($Root,$LocalMcp,$TimeoutSeconds,$Canonical,$Alias,$ClientPath,$Deadline,$ExpectedDaemonProcess)[void]$script:aliases.Add($Alias);$script:lastExpectedDaemonProcess=$ExpectedDaemonProcess;$true }
  $script:aliases=[Collections.Generic.List[string]]::new();$script:actions.Clear();$script:fakeMode="official_runtime";$script:fakeListener=New-FakeListener -Pid 21 -MatchesCanonical $true;$script:runtimeResults=@($true);$Mode="recover";$Execute=$true;Invoke-CanonicalStackBootstrap|Out-Null;if($script:actions.Count -ne 0 -or $script:aliases -notcontains "test-alias"){throw "verified canonical daemon restarted or alias was lost"}
  $env:CATDESK_OPENAI_TUNNEL_ID="test";$env:CONTROL_PLANE_API_KEY="test";$script:actions.Clear();$script:aliases.Clear();$script:fakeListener=New-FakeListener -Pid 22 -MatchesCanonical $true;$script:runtimeResults=@($false);Invoke-CanonicalStackBootstrap|Out-Null;if($script:actions.Count -ne 0){throw "unverified external runtime recycled a healthy canonical daemon"}
  Remove-Item Env:CONTROL_PLANE_API_KEY;$script:actions.Clear();$script:fakeListener=New-FakeListener -Pid 23 -MatchesCanonical $true;$script:runtimeResults=@($false);Invoke-CanonicalStackBootstrap|Out-Null;if($script:actions.Count -ne 0){throw "missing external recovery reference restarted a healthy daemon"}
  $env:CONTROL_PLANE_API_KEY="test";$script:actions.Clear();$script:fakeListener=$null;$script:runtimeResults=@($false);Invoke-CanonicalStackBootstrap|Out-Null;if(([string]::Join(",",$script:actions)) -ne "start:--catdesk-daemon"){throw "new daemon was restarted twice"}
  $script:actions.Clear();$script:BootstrapSeams["GuiInteractiveDesktop"]={ $true };$script:fakeListener=New-FakeListener -Pid 31 -MatchesCanonical $true;$script:runtimeResults=@($true);Invoke-CanonicalStackBootstrap|Out-Null;if(([string]::Join(",",$script:actions)) -ne "start:--catdesk-binagotchy-cli"){throw "interactive lifecycle did not launch exactly the Binagotchy console mode"};$script:BootstrapSeams["GuiInteractiveDesktop"]={ $false }
  # T-0317 exact regression: one canonical daemon process is alive but has no
  # loopback listener. Recovery must retire only that attributable stale daemon
  # and launch exactly one replacement.
  $script:actions.Clear();$script:fakeListener=$null;$script:runtimeResults=@($true);$script:BootstrapSeams["DaemonProcesses"]={param($canonical) @([pscustomobject]@{Pid=41;CreationTimeUtc='2026-09-07T00:00:00.0000000Z';MatchesCanonical=$true})};$Mode="recover";$Execute=$true;Invoke-CanonicalStackBootstrap|Out-Null;if(([string]::Join(",",$script:actions)) -ne "stop:41,start:--catdesk-daemon"){throw "stale canonical daemon/no-listener recovery did not converge in one invocation"}
  # T-0325 race: if the selected PID now resolves to a different process
  # instance, fail closed before Kill and before launching a replacement.
  $script:actions.Clear();$script:BootstrapSeams["DaemonProcessInstance"]={param($canonical,$candidate) throw "CatDesk daemon process instance changed before recovery mutation"};try{Invoke-CanonicalStackBootstrap|Out-Null;throw "changed daemon process instance was terminated"}catch{if($_.Exception.Message -match "was terminated"){throw};if($_.Exception.Message -ne "CatDesk daemon process instance changed before recovery mutation"){throw}};if($script:actions.Count -ne 0){throw "changed daemon process instance caused a mutation"}
  # If the exact selected instance simply exited before acquisition, no kill is
  # needed and recovery may launch the one canonical replacement.
  $script:actions.Clear();$script:BootstrapSeams["DaemonProcessInstance"]={param($canonical,$candidate) $null};Invoke-CanonicalStackBootstrap|Out-Null;if(([string]::Join(",",$script:actions)) -ne "start:--catdesk-daemon"){throw "exited stale daemon did not converge without PID-directed mutation"}
  $script:BootstrapSeams["DaemonProcessInstance"]={param($canonical,$candidate) $p=[pscustomobject]@{Id=[int]$candidate.Pid};$p|Add-Member -MemberType ScriptMethod -Name Kill -Value {[void]$script:actions.Add("stop:$($this.Id)")};$p|Add-Member -MemberType ScriptMethod -Name WaitForExit -Value {param($milliseconds)$true};$p}
  # A subsequent healthy observation must be idempotent even if a stale process
  # list would otherwise be available: listener ownership wins and no kill/start occurs.
  $script:actions.Clear();$script:fakeListener=New-FakeListener -Pid 42 -MatchesCanonical $true;Invoke-CanonicalStackBootstrap|Out-Null;if($script:actions.Count -ne 0){throw "repeated recovery duplicated a healthy canonical daemon"}
  # Wrong-path or multiple daemon candidates are never killed automatically.
  $script:actions.Clear();$script:fakeListener=$null;$script:BootstrapSeams["DaemonProcesses"]={param($canonical) @([pscustomobject]@{Pid=43;MatchesCanonical=$false})};try{Invoke-CanonicalStackBootstrap|Out-Null;throw "foreign daemon candidate was auto-repaired"}catch{if($_.Exception.Message -match "foreign daemon candidate was auto-repaired"){throw};if($_.Exception.Message -ne "noncanonical CatDesk daemon process is ambiguous"){throw}};if($script:actions.Count -ne 0){throw "foreign daemon candidate caused a mutation"}
  $script:actions.Clear();$script:BootstrapSeams["DaemonProcesses"]={param($canonical) @([pscustomobject]@{Pid=44;MatchesCanonical=$true},[pscustomobject]@{Pid=45;MatchesCanonical=$true})};try{Invoke-CanonicalStackBootstrap|Out-Null;throw "multiple canonical daemon candidates were auto-repaired"}catch{if($_.Exception.Message -match "auto-repaired"){throw};if($_.Exception.Message -ne "multiple canonical CatDesk daemon processes are ambiguous"){throw}};if($script:actions.Count -ne 0){throw "multiple daemon candidates caused a mutation"}
  # A canonical GUI/non-daemon process is intentionally absent from the daemon
  # candidate set, so it does not prevent launching the missing daemon.
  $script:actions.Clear();$script:BootstrapSeams["DaemonProcesses"]={param($canonical) @()};$script:runtimeResults=@($true);Invoke-CanonicalStackBootstrap|Out-Null;if(([string]::Join(",",$script:actions)) -ne "start:--catdesk-daemon"){throw "non-daemon CatDesk process shape blocked canonical daemon launch"}
  $script:actions.Clear();$script:wakeReady=$false;$Mode="plan";$Execute=$false;Invoke-CanonicalStackBootstrap|Out-Null;if($script:actions.Count -ne 0){throw "plan mode repaired wake runtime"}
  $script:actions.Clear();$Mode="recover";$Execute=$true;Invoke-CanonicalStackBootstrap|Out-Null;if($script:actions -notcontains "wake-repair"){throw "recover mode did not repair wake runtime"}
  $assessmentNode=$ast.Find({param($n)$n -is [System.Management.Automation.Language.FunctionDefinitionAst] -and $n.Name -eq 'Get-CanonicalReleaseRecoveryAssessment'},$true);if($null -eq $assessmentNode){throw 'missing read-only recovery assessment'};$assessmentSource=$assessmentNode.Extent.Text;if($assessmentSource -match 'Start-Process|Stop-Process|Invoke-InterruptedPromotionPairRecovery|Invoke-OrderedOfficialRuntimeMigration|Test-OfficialRuntimeVerified'){throw 'read-only recovery assessment acquired daemon or tunnel authority'}
  if($source -match [regex]::Escape($route)){throw "test route leaked into bootstrap source"};foreach($required in @("--catdesk-daemon","--catdesk-binagotchy-cli","Start-CatDeskBinagotchyGui","catdesk_instruction","delegated_run_list","Get-VerifiedBuildFingerprint","healthz","readyz","Get-OfficialRuntimeVerification","Get-RedactedReadinessFailureGate","Save-RedactedRecoveryEvidence","Invoke-BoundedTunnelClient","Invoke-BoundedCodexProbe","Initialize-BoundedNativeProcessType","Invoke-SilentLoopbackHttp","ConvertTo-NativeCommandLineArgument","process.Kill()")){if($source -notmatch [regex]::Escape($required)){throw "missing $required"}};if($source -match "& \$clientPath runtimes status"){throw "unbounded runtime status remains"};if($source -match '& \$codex\.Source'){throw "unbounded Codex prerequisite probe remains"};if($source -match "--auto-start-computer"){throw "legacy TUI launch remains"}
} finally {if($hadTunnelRef){$env:CATDESK_OPENAI_TUNNEL_ID=$priorTunnelRef}else{Remove-Item Env:CATDESK_OPENAI_TUNNEL_ID -ErrorAction SilentlyContinue};if($hadControlRef){$env:CONTROL_PLANE_API_KEY=$priorControlRef}else{Remove-Item Env:CONTROL_PLANE_API_KEY -ErrorAction SilentlyContinue};if($hadCodexExecutable){$env:CATDESK_CODEX_CLI_EXECUTABLE=$priorCodexExecutable}else{Remove-Item Env:CATDESK_CODEX_CLI_EXECUTABLE -ErrorAction SilentlyContinue};Remove-Item -LiteralPath $root -Recurse -Force -ErrorAction SilentlyContinue}
Write-Output "canonical bootstrap behavioral tests passed"
